### ISSUE TITLE
Item Usage: Eul's

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#10]
Let's write some rules for using Eul's - especially for comboing on Lina

**Comment by Keithenneu** [comment]
Situations that come to mind:
- disrupt channeling enemys
- stop chasing enemy while on retreat
- stop retreating enemy when chasing
- setup hard to land spells
- kite enemy carries
- disable enemies

Using it as part of a combo, and for chasing/retreating should be the easiest for now.
Using it as a generic setup would require some advanced fighting logic. Not sure what the state of this is atm.
One could start with building setup logic. Chain stuns, euls, disruptions, skillshots etc. to minimize the overlapping time. Some spells don't allow overlap (euls, arrow,..). While some enemies might escape without overlaps.

I don't know what the state of fighting logic is at all. Just felt like writing it down.

**Comment by pbenologa** [comment]
I've created a UseDefensiveItems(enemy, triggerDistance) method in item usage not sure if there are existing ones but i made this for hurricane pike use on enemies when they close to you. See on my fork.

**Comment by Nostrademous** [comment]
https://github.com/Nostrademous/Dota2-FullOverwrite/commit/39b0b3ff10d58e700761f151b5eba3432961aa61

Did all of @Keithenneu suggestions with the exception of "combo/hard-to-land spells". I think those will come at the abilityUse_* level that check for eul's modifier on target and get remaining duration.
