### ISSUE TITLE
Script reload

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#104]
What are our chances of making the scripts not break down entirely on a script reload?
It really hurt's to wait 10 minutes every time you fixed a simple typo.

**Comment by Nostrademous** [comment]
is there a way to detect a reload happening like OnStart() and OnEnd()? We have so much data we store that would need to be repopulated after a reload.

**Comment by Keithenneu** [comment]
We could set a isInitialize variable and check if wether the gametime is greater than it should for the game start.
It's not that high priority, but i think it would be nice to have in the future.
