### ISSUE TITLE
Get Tower vectors from the api

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#107]
the vector for the dire top tier 1 seems to be off. (close to radiant tt1).

I'll have a look at this at home.

**Comment by Nostrademous** [comment]
We probably shouldn't use the hardcoded Vector values like we are in utils anyways.

As of December 22nd the following constants were available via the API:

TOWER_TOP_1
TOWER_TOP_2
TOWER_TOP_3
TOWER_MID_1
TOWER_MID_2
TOWER_MID_3
TOWER_BOT_1
TOWER_BOT_2
TOWER_BOT_3
TOWER_BASE_1
TOWER_BASE_2
GetTower( int iTower, int iTeam ) : handle

BARRACKS_TOP_MELEE
BARRACKS_TOP_RANGED
BARRACKS_MID_MELEE
BARRACKS_MID_RANGED
BARRACKS_BOT_MELEE
BARRACKS_BOT_RANGED
GetBarracks( int iBarrack, int iTeam ) : handle

GetAncient( int iTeam )

**Comment by Nostrademous** [comment]
As of January 12

SHRINE_BASE_1, SHRINE_BASE_2, SHRINE_BASE_3, SHRINE_BASE_4, SHRINE_BASE_5, SHRINE_JUNGLE_1, and SHRINE_JUNGLE_2 are available too:

GetShrine( int iShrine, int iTeam ) : handle

**Comment by Keithenneu** [comment]
I'll check if GetLocation() is available for enemy structures by todays update

**Comment by Keithenneu** [comment]
Okay, it is.

**Comment by Keithenneu** [comment]
GetMaxHealth() isn't available though.

**Comment by Nostrademous** [comment]
GetHealth() should be (perhaps only if visibile)

**Comment by Keithenneu** [comment]
i was talking about fogged enemy buildings

**Comment by Nostrademous** [comment]
Okay, well the max health is hardcoded, so we could use hardcoded variables for that. Perhaps remember last seen health value via our variables? They will probably not fix this as some buildings, like melee barracks heal and as a player in game you don't see their current health value until you have vision

**Comment by Keithenneu** [comment]
for towers, all this is implemented. Just have to think about how to merge other buildings into the code, without making it super ugly.
I'l just mirror our teams maxhealth to the enemys.

**Comment by pbenologa** [comment]
For barracks, I think last seen health will do, then calculate current health by time passed multiplied by its regen rate?

**Comment by Keithenneu** [comment]
yeah, sure.

**Comment by Nostrademous** [comment]
GetHealthRegen( ) : float - unit scoped. tower's are units. might work, might not...

**Comment by Keithenneu** [comment]
works on your own buildings. might work on enemy buildings in sight.

**Comment by pbenologa** [comment]
The only thing that would mess with it is if the enemy has treant since we cant get details of enemy tower when not in sight

**Comment by Keithenneu** [comment]
@Nostrademous I think you swapped team and buildingId. Team should be first.

**Comment by Nostrademous** [comment]
Okay, possible. Would make sense.
