### ISSUE TITLE
GetDestroyableTower

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#110]
AFTER loosing a tower I see the bug below:

Bug:

[VScript] Script Runtime Error: ...eta\game\dota\scripts\vscripts\bots/buildings_status.lua:169: attempt to index a nil value
stack traceback:
	...eta\game\dota\scripts\vscripts\bots/buildings_status.lua:169: in function 'GetDestroyableTowers'
	...2 beta\game\dota\scripts\vscripts\bots/decision_tree.lua:418: in function 'Determine_ShouldUseGlyph'
	...2 beta\game\dota\scripts\vscripts\bots/decision_tree.lua:230: in function 'Think'
	...ota 2 beta\game\dota\scripts\vscripts\bots\bot_viper.lua:60: in function <...ota 2 beta\game\dota\scripts\vscripts\bots\bot_viper.lua:57>

the "tower" array refrenced on line 169 of building_status.la is only ever populated once since we never force an update (as far as I see). That intended?

**Comment by pbenologa** [comment]
This should be check at what interval? Maybe when a tower gets destroyed?

**Comment by Nostrademous** [comment]
it looked like the check was supposed to be at 0.5 second interval, but the comparison sign is then backwards. not my code so wasn't sure.

**Comment by Keithenneu** [comment]
towers was intended to work like this, yes.
Not sure if it would be useful to have an updated list around. Thoughts?

Use `if GetHealth(team, id) > -1 and GetHandle(team, id) ~= nil and (not GetHandle(team, id):IsInvulnerable()) then`. I'll open a PR as well, but it might take some hours to be merged.

Which interval are you talking about?

**Comment by Keithenneu** [comment]
You could also use GetDestroyableTowers(), which relies on cached values, instead of ApiCalls, and returns all vulnerable buildings (Including shrines.).
