### ISSUE TITLE
Jungling bug

### ISSUE THREAD

**Issue by pbenologa** [Nostrademous/Dota2-FullOverwrite#112]
Jungling is currently bug from my observation this error pops after stack state or wait state.

> 
[VScript] Script Runtime Error: ...eta\game\dota\scripts\vscripts\bots/global_hero_data.lua:23: attempt to index a nil value
stack traceback:
	...eta\game\dota\scripts\vscripts\bots/global_hero_data.lua:23: in function 'GetVar'
	...eta\game\dota\scripts\vscripts\bots/jungling_generic.lua:78: in function <...eta\game\dota\scripts\vscripts\bots/jungling_generic.lua:62>
	...eta\game\dota\scripts\vscripts\bots/jungling_generic.lua:207: in function 'Think'
	...2 beta\game\dota\scripts\vscripts\bots/decision_tree.lua:1076: in function 'DoJungle'
	...2 beta\game\dota\scripts\vscripts\bots/decision_tree.lua:352: in function 'Think'
	...beta\game\dota\scripts\vscripts\bots\bot_bloodseeker.lua:70: in function <...beta\game\dota\scripts\vscripts\bots\bot_bloodseeker.lua:67>

**Comment by Keithenneu** [comment]
I wasn't able to reproduce this.

**Comment by pbenologa** [comment]
After playing games this did not occur again. Weird.

**Comment by Nostrademous** [comment]
It happens if you have a bot player that we did not implement yet on your team. I have a fix for it I will push

**Comment by pbenologa** [comment]
I see. So that's why it only occured when bs and drow was the only custom bot on the team.

**Comment by Nostrademous** [comment]
Yes, because we do not call gHeroVar.Init() for those bots ever to setup their global data table. As a result anywhere else in code where we later iterate the list returned by GetUnitList(ALLIES) and we check a global data table using setHeroVar or getHeroVar it will fail to find the bot's index.
