### ISSUE TITLE
Recent result 

### ISSUE THREAD

**Issue by pbenologa** [Nostrademous/Dota2-FullOverwrite#115]
So far so good. In my last run they won by split pushing. Lol

http://imgur.com/a/5TGBq

**Comment by Nostrademous** [comment]
Hehe. Nice. Try sending Lina mid as a core, drow bot as HC and replace AM with a default bot support.

**Comment by pbenologa** [comment]
Ill try that once you push the fix for the jungling bug with non custom bots

**Comment by Nostrademous** [comment]
Not at home for another 3 hours

**Comment by pbenologa** [comment]
Well it's already 10pm here, so maybe by tomorrow morning I can continue that. 😂

**Comment by Nostrademous** [comment]
Hah, 9am here

**Comment by pbenologa** [comment]
Last run on my latest PR changes. Still needs to implement orb walking/kiting but nonetheless bot is working great. They won by splitpushing again. 

[http://imgur.com/a/xvKbs](url)
