### ISSUE TITLE
Make Bots react while waiting for runes

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#117]
I played a match in the dire team. I decided to snatch a rune, but your bots were there. lina and am. I could nearly kill am, because they did not react at all.

**Comment by pbenologa** [comment]
Try getting near drow. As far as i know they dont react to enemies nearby unless they engage in a fight.

**Comment by Nostrademous** [comment]
I am fixing that soon. They only engage if they can kill a target in 5 seconds or less currently. This will be changed to "if you collectively do more damage then you take in X seconds, fight".

**Comment by Nostrademous** [comment]
Hopefully fix, will reopen if not.
