### ISSUE TITLE
Drow - Gust Use

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#119]
Implement Gust when

1) retreating and enemy on his face/back
2) when fighting and enemy HasStun()

**Comment by pbenologa** [comment]
Regarding on the Gust when retreating where should I put this? Since in the ability_usage_drow_ranger.lua the bot only uses Q or W when it has a definite target. And I assume when retreating the "target" is reset to nil.

**Comment by Nostrademous** [comment]
I do something like this for Light Strike Array for Lina

-- If we're seriously retreating, see if we can land a stun on someone who's damaged us recently
    local tableNearbyEnemyHeroes = npcBot:GetNearbyHeroes( nCastRange + nRadius + 200, true, BOT_MODE_NONE );
    for _,npcEnemy in pairs( tableNearbyEnemyHeroes ) do
        -- FIXME: This logic will fail against Heartstopper Aura or Radiance probably making us LSA all the time
        --        as we take damage and are below 50% health
        if npcBot:WasRecentlyDamagedByHero( npcEnemy, 2.0 ) and (npcBot:GetHealth()/npcBot:GetMaxHealth()) < 0.5 then
            if CanCastLightStrikeArrayOnTarget( npcEnemy ) and abilityLSA:GetCastRange() > GetUnitToUnitDistance(npcBot, npcEnemy) then
                -- NOTE: LSA cast point is 0.45, hit delay is 0.50
                local locDelta = npcEnemy:GetExtrapolatedLocation(0.95)
                return BOT_ACTION_DESIRE_MODERATE, locDelta
            end
        end
    end

**Comment by pbenologa** [comment]
I see. I'll read up on lina's ability usage. As for the FIXME note you got there you can fix that by checking if bot has modifier (Heartstopper Aura or Radiance).
