### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#127]
I updated for all the changes in the new patch, but something went wrong. The game will crash at times without a traceback... so hard to solve. Need help.

**Comment by pbenologa** [comment]
Bug was caused by the update. We'll have to wait for valve to fix this.

**Comment by Nostrademous** [comment]
I don't see an official statement from valve if this being the case.

**Comment by Nostrademous** [comment]
There is some strange bugs right now with bots. Not our fault necessarily.

Default Bots vs Default Bots crash the game (so definitely not our fault).

Our Bots vs Our Bots don't crash, but handles are corrupted (probably b/c of Valve and not us)

**Comment by Keithenneu** [comment]
ChrisC seems to be fixing handles right now.

**Comment by Nostrademous** [comment]
Once they fix this we still might have problems... this is because enemy_data.lua stores the enemy.Obj which is the handle to the enemy. They now destroy handles as soon as you loose vision of that enemy or the enemy makes illusions. I went through the code and tried to make sure we check the Obj before using it to be safe, but depending on how they "destroy" the handle it might or might not be safe for us. 

Just an FYI

**Comment by Nostrademous** [comment]
they found the bug, shipping a fix sometime today.

**Comment by Nostrademous** [comment]
Bots are working... so far 4 min into my game and no crashes/errors.

**Comment by Nostrademous** [comment]
Got a traceback crash when Bloodseeker tried to gank  a target (Sand King) who used his sandstorm to go invis... handle was destroyed. Apparently rather then checking if "target.Obj == nil" I should be doing "target.Obj:IsNull()". Testing now.
