### ISSUE TITLE
Outsource common bot functions

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#13]
Is there a way of outsourcing the ItemPurchaseThink, SaveUpdates and LoadUpdates (Maybe others as well)?
Having these in each bots files seems a little redundant.

**Comment by Nostrademous** [comment]
The SaveUpdates and LoadUpdates for sure and should be really easy to outsource to utility.lua

ItemPurchaseThink i will have to see and think about but anything is doable

**Comment by Nostrademous** [comment]
Completed - will be in next check in
