### ISSUE TITLE
Tango Use - Check Z-Axis for nearest Tree

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#132]
Sometimes the "nearest" tree by distance is on a cliff I'm standing next to... to eat it I path all the way around to climb the hill just to eat the tree. Implement checking that z-axis of tree == my z-axis when sorting trees for nearest.

**Comment by Nostrademous** [comment]
I had to make a change as U.GetHeightDiff() takes two locations, not a unit handle and a location. Watching it in game it doesn't seem to work.

Perhaps we should use the unit-based (heroes and trees are both considered units) GetGroundHeight() API

**Comment by Nostrademous** [comment]
Actually, it is probably best to change U.GetHeightDiff() to take two unit handles and then call GetGroundHeight() on each. I have a feeling tree location vectors have 0.0 for all z-axis values.

**Comment by pbenologa** [comment]
Yes i think it's the best approach rather than using unit location.

**Comment by Nostrademous** [comment]
Fixed.
