### ISSUE TITLE
Additions for later times

### ISSUE THREAD

**Issue by PaulMaederer** [Nostrademous/Dota2-FullOverwrite#137]
How about kiting / run and shoot and run and shoot movement for ranged carries like DrowRanger / Sniper?
How about hotd on Supports IF their carry has a good way to  clear them.
How about Carries farming until they have EDIT: "their key-items" and their Support only helping if the carries Need help in lane and else pressure the enemy Team?
How about detection against invis heroes (on Supports only)? 
How about dewarding?
How about smoke-ganks before Minute 0?
How about smart picking? -> early rosh, push Teams, drow strats....
How about securing runes for mid? Well not in this patch but ...
How about a captain's mode picker? I saw one already, but he just picked random heroes I think. Counter picking would be really interesting, maybe with the help of dotabuff counterpickssystem.
How about an easteregg in which bots tell you you should be more ... polite if you curse.
more ideas follow soon(tm) :D

**Comment by Nostrademous** [comment]
Ideas are great... I also need more help implementing them though. Feel free to jump in and contribute if you are able.

**Comment by PaulMaederer** [comment]
Well, certainly not good Sir. 
I don't understand lua, I only do C# in a full time Job right now...
Sorry about that.
But I USED to Play a lot of dota, and mostly with / against bots.
So I am really looking Forward to this, this Looks very promissing. 
Also sorry about the spelling, my German auto-correction fucks this up.

**Comment by pbenologa** [comment]
I'll try to work on some the listed up there. I wasnt able to do things in the office anymore since work started to pour in. 😊

**Comment by ByBurton** [comment]
Wow, well, I gave up on trying to get into lua-scripting.
I am too stupid. Also well yeah stuff...
But I love your list, and I would also maybe add support for more than one human player, because I have a friend that wants to play these bots with me regulary.... and it never works :/

**Comment by Nostrademous** [comment]
Someone was supposed to check in a fix for that... ... ... as we have it working just not commited
