### ISSUE TITLE
Improve PositionAlongLane()

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#142]
In utility.lua:

function U.PositionAlongLane(npcBot, lane)

It's a while loop that iterates 100 points (0.0 to 1.0 in 0.01 increments) to find the nearest distance from each location to our bot's current location to determine where we are percentage wise in our lane.

This happens every frame for every bot that's "in a lane". 

It is inefficient. Please fix using 1-3 reference distances from fountain to get a very accurate result and speed this up.

**Comment by Nostrademous** [comment]
http://dev.dota2.com/showthread.php?t=277505

**Comment by RabidCicada** [comment]
As noted...closed
