### ISSUE TITLE
Chasing enemy hero through the WHOLE map and enemy base

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#149]
Title says everything.
Viper chased nearly dead PA through the whole fucking map, and through the base and died in front of the fountain...

Your bots are too aggressive in nearly every way :(.
I know this is a gigantic project and stuff, but I just can not help you .... :(
I can only test stuff and inform you about stuff I notice...

**Comment by Nostrademous** [comment]
This happens when a bot uses an ability that he is not in range of (like Drow Ranger using Frost Arrows on enemy who starts retreating. Valve's code will chase the hero to get in range to cast the ability. Will fix

**Comment by Nostrademous** [comment]
Should be fixed.
