### ISSUE TITLE
ReWrite Decision Logic

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#150]
It needs to be done for several reasons:
* efficiency
* better team-wide versus hero-specific action resolution
* sanity / code clarity
* alignment with other Bots that do Mode Over-Writes for portability reasons.

Here is the Wiki Link with my thoughts:
[WIKI LINK](https://github.com/Nostrademous/Dota2-FullOverwrite/wiki/Team-and-Hero-Decision-Evaluation)

**Comment by Nostrademous** [comment]
Feedback is much welcome.

**Comment by Keithenneu** [comment]
Haven't done anything in the past weeks, so I'm not really up to date. just one thing that came to mind:

> -- If we see a rune, determine if any specific Heroes should get it 
> -- (to fill a bottle for example). If not the hero that saw it will get it.
> ConsiderTeamRune()
Should predict and/or secure runes as well. Should be possible to add this later one. Iust wanted to write it down to make sure the code will be able to handle things other than just picking up the rune.

PS: 2 more weeks and I'll be able to work on the bots again :D

**Comment by Nostrademous** [comment]
No worries, school is way more important than this.

**Comment by Nostrademous** [comment]
Laning is in
Jungling is in
Warding is in
Grabbing Runes (now assigned at the team level) is in -- although don't check for bottles yet, don't have preemptive timer based moving yet
Retreat Code is in
Shrine Use is in with code to track team-wide shrine desire (bots will wait for team-mate at shrine if other bots could use a heal)

**Comment by Nostrademous** [comment]
Attack is in

I pushed the current version I have. It is playable and much more efficient so far (I don't see any of the console message saying I'm over 2.0ms anymore).

It still needs a lot of polish and tweaking.
