### ISSUE TITLE
Do not try to use shrine if on cd

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#151]
Well, headline says everything....

also, Drow Ranger seems to be afk too in tower range / or in the lane in general like 80% if the time, and Viper keeps feeding.

**Comment by Nostrademous** [comment]
Yeah, I did a push this morning to fix some of those. The AFK drow I need to diagnose still. There is a check for shrine cooldown in place so not sure why they sometimes sit there doing nothing. It might be a bug in my code and they are waiting on a teammate that will never come.

**Comment by ByBurton** [comment]
Yeah, I also have no idea why she does that.
Also it would all be so much better for the bots, if Viper would not feed so much. The enemy PA had 32 - 0 at the end of my last test.

**Comment by PaulMaederer** [comment]
The most important Thing seems to be the Viper that Feeds, and maybe that you can not Play it with other human Players. I wanted to show These bots to my friends, but they do not pick heroes....

**Comment by Nostrademous** [comment]
once I find time for a bit more testing I will have an update.

I believe viper feed is fixed, drow AFK fixed, shrine use on CD fixed, and more. Also added back Lane Pushing and Ganking.

Just like I said, need time to test to make sure nothing is broken.
