### ISSUE TITLE
Bots running past towers

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#152]
E.g. Drow Ranger completely ignores the tower, runs past and waits for creeps.
E.g.2 Cm standing under tower and running back and forth.

But I am impressed about the changes, viper is feeding less, and Drow Ranger is getting some farm finally.

I don't want to address the other things, as I wrote them in too many other issue posts already...

**Comment by Nostrademous** [comment]
Should be fixed... with maybe one exception (being when they are last hitting creeps)
