### ISSUE TITLE
Porting Mode Usage 

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#159]
Just an FYI to anyone contributing - I'm in the middle of fixing up the directory structure, mode calling for the framework, and how itemPurchasing is called. On travel currently and doing most of my coding on the plane so cannot test. The plan is that we will have better file organization and better (more similar to mode-level over-write) mode calling.

**File Structure:**
3 sub-directories are getting added to help declutter the main bots/ directory
bots/itemPurchase/<bot_name>.lua
bots/abilityUse/abilityUse_<bot_name>.lua
bots/modes/<all mode files>

**Mode Calling:**
Currently the top-level hero think function evaluates each mode and returns the mode constant (specified in constants.lua) and the desire value of that mode, eventually returning the mode constant with the highest mode value. Next, in decision_tree.lua, we have a large if-elseif chain checking each mode constant to see which one we want to execute and invoking it (i.e., DoUseShrine(hBot)). This will be changed so that the top level hero think function will return a handle to the mode object instead, each mode will have it's own module which will require a "Think()", "OnStart()" and "OnEnd()" at minimum. "OnStart()" and "OnEnd()" exist to allow for easy cleanup of any hero or global variables that need to be initialized/purged when transitioning to and from the mode.

**Item Purchasing:**
Currently Item Purchasing is named to directly over-write the _item_purchasing_heroName.lua_ which makes it disconnected from the full-overwrite calls made by bot_heroName.lua which gets called separate from it. This is getting changed so that the "decision_tree" (which will be renamed to "decision") makes calls against it when it wants to rather than the Valve scheduled ItemPurchaseThink() of each hero. This will allow better control of when we invoke it as well as allow our decision-making about wanting to transition to SECRET or SIDE SHOPs visits integrated with all the other modes.

**Comment by Keithenneu** [comment]
Sounds good to be.
Hopefully, this will fix/allow fixes to some of the current mode switching issues (Bot standing there afk, being unsure of what to do).

**Comment by Nostrademous** [comment]
Yes, that's one of the main motivating factors of this. Easier debugging of such bugs.. which are usually caused by the failure to clear some hero-specific variable.

**Comment by Nostrademous** [comment]
made a separate branch for the upcoming new code: https://github.com/Nostrademous/Dota2-FullOverwrite/tree/new_mode_format

**Comment by Nostrademous** [comment]
did a larger push just now with an example of how new modes allow for over-rides - check modes/retreat_bloodseeker.lua and how it is called in hero_think.lua.

At this point Invoker & BS are the two bots enabled under new format... 
Jungling, Laning, Retreat, Rune use seem to be working
Warding, Roaming should work - haven't tested yet

**Comment by Nostrademous** [comment]
Roaming is in. Warding still untested.
Fighting is in.

Debugging prints current state and if retreat, roam or fight extra info

**Comment by Keithenneu** [comment]
Jungling is buggy (bs idles somewhere as he is retreating from a creep). Item buying is still weird.
Do you have any non pushed changes on this? I don't want to fix it if you already did.

**Comment by Nostrademous** [comment]
I don't for jungling or retreating. I do realize there are still buggy a bit... and the reality is that they were buggy in the "master" branch as well, but now it should be much easier to debug them.

**Comment by Nostrademous** [comment]
I have some uncommitted changes to glyph use

**Comment by Nostrademous** [comment]
my plan is to add "Desire()" to all the modes (like it exists for "retreat" and "fight" mode) currently ported, then port over "lane push" and "shrines", then port over the remaining bots we have implemented, then go back and debug anything that looks broken... feel free to help out with any of these just by dropping a line

**Comment by Nostrademous** [comment]
regarding retreat bug, the bug is in how "retreat creep" is done I think. We might be reaching the location we were retreating to but not meeting other parts of the conditional check.

**Comment by Keithenneu** [comment]
Are jungling, ganking/roaming or Defending ported? If not, I'll give it a try.

**Comment by Nostrademous** [comment]
jungling and roaming are, defending is not

**Comment by Keithenneu** [comment]
On it.

**Comment by Nostrademous** [comment]
item buying as far as I saw is only weird for bloodseeker, not invoker.

**Comment by Keithenneu** [comment]
I'll try to port cm, viper and drow first. Two aren't really enough for propr defense testing.

**Comment by Nostrademous** [comment]
that will be harder than it seems... I can take care of it later today. There is a bit of inside knowledge you need to make it easy.

**Comment by Keithenneu** [comment]
I'll give it a try with CM, and see how far I get.

**Comment by Nostrademous** [comment]
delete the item_purchase_crystal_maiden.lua at the top level or you will have weird item purchase issues (after you implement the itemPurchase/crystal_maiden.lua)

**Comment by Keithenneu** [comment]
sure, thx

**Comment by Nostrademous** [comment]
for abilityUse/*.lua ... target.Obj no longer exist... they should all be "target" (for now). I need to create a new global data holder for enemies by enemyID (since the handles get destroyed as soon as we lose line of sight) and when I do I will have to update all the code to use it.

**Comment by Keithenneu** [comment]
I think I got her working. She can't decide wether she wan't to ward or to lane.
There are still some bugs with the target.Obj and seomthing with retreat lane.
Not sure if they are caused by my CM port or something else.
I'll create a PR anyway.

**Comment by Keithenneu** [comment]
Just noticed I messed up my branches.. I'll run another test.

**Comment by Keithenneu** [comment]
ok, branches weren't the issue.
Looks like HeroVar "RetreatLane" is nil in some cases (invoker keeps getting type mismatch errors)
The PR is #161

**Comment by Nostrademous** [comment]
okay, fixed the warding issue, minor fixes to CM ability use (some left over target.Obj)

will need to work on the RetreatLane issue

**Comment by Keithenneu** [comment]
Drow has a function drowRangerBot:Determine_ShouldJungle(bot).
As this should be the same logic for every carry/hero, and I don't believe it's needed right now, I'd throw it out. Opinions?

**Comment by Nostrademous** [comment]
I would toss for now, we have repo to get it back later if we need it.

**Comment by Keithenneu** [comment]
added viper and drow: #162 
something was horrible wrong with the laning (looked like they shared a common state, so you might have fixed it already).

**Comment by Nostrademous** [comment]
fixed some drow/viper stuff; fixed a thrown error in "shop" mode. Shop still seems to be broken. 
Item purchases seem broken.

**Comment by Keithenneu** [comment]
shop mode desire doesn't check if we have enough money. -> bot enters shop mode, does sideShoptThink, realizes he's to poor, and does nothing.
Not entirely sure if the money check or the does-nothing is the issue / not as it's supposed to be.

**Comment by Keithenneu** [comment]
Here's a PR for the money thing though: #163
There is still something wrong with the 'UpdateTeamBuyList' call (shop.lua:107). I noticed it's local, not sure if that's a problem.

**Comment by Nostrademous** [comment]
Fixed the team buying thing. Thanks.

**Comment by Keithenneu** [comment]
I still get UpdateTeamBuyList nil errors.

**Comment by Nostrademous** [comment]
Yeah, no clue. Will have to dig deeper.

**Comment by Nostrademous** [comment]
Still need to fix those errors but the latest check in into this branch has some success against unfair bots.

Just watched a 46 min game where our bots won vs WD, SF, Tide, Kunkka, Zeus

Issues I saw:
* UpdateTeamBuyList error (needs to be fixed as it prevents buying of other items) - at end of game Viper had 20k gold saved up and was still using treads, stout shield, Basi, slippers of agility and a ironwood -- yeah, we won with 3 out of 5 heroes having starting items
* Bloodseeker at one point sold his Shadow Blade to make room for an AC... while leaving an IronWood in his backpack and keeping an Iron Talon
* Bloodseeker had enough money at one point to buy the last piece for AC (from secret shop) but the mode desires weren't high enough I guess, cause he didn't track to Secret shop but rather continued lane pushing
* Blink Dagger - not being used by Invoker
* Abyssal - not being used by Bloodseeker
* No lane defense, no ally defense
* Invoker's extrapolated sun strike location seem to be off (true for other spells as well)
* Drow - I think b/c he uses frost arrow so much he can get stuck in "IsCastingAbility" or "IsUsingAbility" so he won't stop casting it and run away as mode is telling him to do and just dies
* TPing to towers into 5 enemies - insta-death

**Comment by Keithenneu** [comment]
Pushing is missing as well.

**Comment by Keithenneu** [comment]
Another thing, which makes defending kinda hard: they don't really carry tp scrolls. Just some bots happen to have one available. Would be great if you could look into this.

**Comment by Nostrademous** [comment]
Pushing is in... (although it has bugs).

Yeah, I hear you on the TP thing...

**Comment by Nostrademous** [comment]
alright, I am pretty sure I have the UpdateTeamBuyList error fixed in my next push (testing now)

**Comment by Nostrademous** [comment]
okay, pushed

when I mean "pushing is in" I mean localized lane pushing, not smart team-assembly style pushing

**Comment by Keithenneu** [comment]
I can't find any push code. Where does it life?

**Comment by Keithenneu** [comment]
I mean, is there anything else than killing creeps much faster when we are supposed to push?

**Comment by Nostrademous** [comment]
ideally it should be calling in other heroes (at least support) to help push.... strategic view of the game.

modes/pushlane.lua

**Comment by Keithenneu** [comment]
ah damnit, missed that one in the commit list. thx.

**Comment by Keithenneu** [comment]
Is there anything missing in terms of porting old stuff though?
Defending was never in, so that's kind of a new feature.
If not, I'd suggest we go back to `master`.

**Comment by Nostrademous** [comment]
just porting Lina (and other bots) for abilityUse and new bot_"heroname".lua

**Comment by Nostrademous** [comment]
ported all the bot_*.lua files... still need to do abilityUse/abilityUse_*.lua

**Comment by Nostrademous** [comment]
FYI - I merged the branches.
