### ISSUE TITLE
item buying is broken (march 2 update)

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#160]
Looks like the latest patch broke something. I added ItemPurchaseThink() to the bots Tkinh method, but nothing happens. Can't figure out what's wrong. Any ideas @Nostrademous ?

Edit: BS for example buys brown boots and tangos, some stuff, and brown boots again.

Edit2: Not quite sure how lua require works. I guess the ItemPurchaseThink Methods of different heroes are getting messed up?

**Comment by Nostrademous** [comment]
Yeah... I noticed this too today.

**Comment by Keithenneu** [comment]
Yup, giving them unique names works. I'll use it as a quick and dirty fix, as you are probably messing with these files anyway right now :D

**Comment by Nostrademous** [comment]
are you running the new branch?

**Comment by Keithenneu** [comment]
nah, I'm working on the tower stuff in an older branch in my fork. (I you can give a branch in this repo I'd use this one).

**Comment by Nostrademous** [comment]
https://github.com/Nostrademous/Dota2-FullOverwrite/tree/new_mode_format

**Comment by Keithenneu** [comment]
Yeah, I know this one. But the tower defend code is messed up big time, and the api calls are super buggy. so i decided to use a branch for tower stuff exclusively.

**Comment by Nostrademous** [comment]
heh, I'm not sure how to give you a branch

**Comment by Keithenneu** [comment]
No idea as well. I guess I'll keep working on my fork then.

**Comment by Keithenneu** [comment]
hm, bots are still buying weird stuff with uniqe ItemPurchaseThink methods. Slightly less random though. I have no idea what's going on.

**Comment by Nostrademous** [comment]
is your debugging.lua code working? I don't see anything drawn on the screen.

**Comment by Keithenneu** [comment]
it's not activated (no one writes anything).

**Comment by Keithenneu** [comment]
btw it writes at x=1600.

**Comment by Keithenneu** [comment]
i also added a wiki entry, in case u want to check the usage

**Comment by Nostrademous** [comment]
I'll check it out, but we really should come up with a way to obtain or specify the resolution.

**Comment by Keithenneu** [comment]
currently it''s a single variable at the top of the file. We might want to think about a settings file anyway.

**Comment by Keithenneu** [comment]
And I think I saw someone asking for some screen stuff in the api request thread.

**Comment by Nostrademous** [comment]
I checked in a debugging info that should work (in my branch) - although I haven't tested it and won't be able to until tomorrow.

**Comment by Keithenneu** [comment]
just `hMyBot`, not `hMyBot.Name`. although I'm thinking about changing this, in case we don't have a handle.
Not sure if you need to pu `debugging.` in front of the call.

**Comment by Keithenneu** [comment]
Looks good.

**Comment by Keithenneu** [comment]
Although I think this should be placed in another file, so that debugging.lua is a pure utility/library style module.
With the new directory structures it's probably a good idea to make more, shorter files anyway.

**Comment by Keithenneu** [comment]
crap, wrong button. I should probably go to sleep.

**Comment by Nostrademous** [comment]
so I just tested, the text appears in red on the screen, but at my resolution is rather tiny and appears in the middle of the screen and each entry takes up two lines (which I wasn't expecting).

I am running at 3440 x 1440 (ultra-wide-screen)

**Comment by Keithenneu** [comment]
The two lines are fixed for simplicity. Using something else shouldn't be to hard to implement.
Red appeared to have the best contrast  (I tried to draw a shadow - didn't really work as the characters are to small).
Well, who expects that kind of resolution... If we want a font size parameter we gotta request it, I guess.

**Comment by Nostrademous** [comment]
It is the next progression: 4x3 --> 16x9 --> 64x27

**Comment by Nostrademous** [comment]
fixed item purchasing - it was the default ItemPurchaseThink() fighting our think() for buying items.
