### ISSUE TITLE
hero_selection

### ISSUE THREAD

**Issue by CsharpNoobDude** [Nostrademous/Dota2-FullOverwrite#164]
Soo, I noticed you have bloodseeker in bottom lane, although he is jungle. Well, technically he IS bottom, but ..
Is there going to be a dynamic picking sometime in the further future?

**Comment by Nostrademous** [comment]
That's the plan. Finishing modes and bug fixing is top priority. Then add some more heroes so that we can have dynamic picking.

**Comment by CsharpNoobDude** [comment]
Okay, thank you.
I am looking forward to it :).
There are cool apps for counterpicking and picking.
Earth vs pl just as ann example.
Or global team strat, Drow strats, push strats, ANTI-push strats......

**Comment by CsharpNoobDude** [comment]
That is actually something I would like to do, I have holidays the next two weeks too.

**Comment by Nostrademous** [comment]
That would be helpful, we would have to figure out how to represent that information in code, but just having the brainstorm of the concept would be cool.

One thing I will point out:
C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\npc\npc_heroes.txt

In that file for each hero (let's take Antimage as an example) there is a "Bot" section provided by Valve.
It provides something like below:
`		"Bot"
		{
			"HeroType"		"DOTA_BOT_HARD_CARRY"
			"LaningInfo"
			{
				"SoloDesire"		"1"
				"RequiresBabysit"		"2"
				"ProvidesBabysit"		"0"
				"SurvivalRating"		"2"
				"RequiresFarm"		"2"
				"ProvidesSetup"		"0"
				"RequiresSetup"		"1"
			}
		}`

We could extract that information to build a "good" team.

**Comment by Keithenneu** [comment]
Please keep that list in a machine readable format.

**Comment by Nostrademous** [comment]
updated hero_selection.lua to make it easier to implement strategic team composition.

**Comment by Nostrademous** [comment]
Added Spirit Breaker to Offlane list.

**Comment by Nostrademous** [comment]
@CsharpNoobDude are you working on this or no?

**Comment by CsharpNoobDude** [comment]
No, sry I just don't have a correct idea how to start yet...
And I did not have any time recently. Sorry.
ByBurton wanted to help too, right? Maybe she can start already...

**Comment by Nostrademous** [comment]
Ok, no problem, I will close this out for now and we can revisit in the future.
