### ISSUE TITLE
Perfomance issues

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#165]
I've got about 5ms on every single Think(), resulting in a minor lags.

For reference:
```
function Think()
    for i = 1, 500, 1 do
        local nearbyEnemyHeroes = GetUnitList(UNIT_LIST_ALL)
        for _, e in pairs(nearbyEnemyHeroes) do
            if e:GetPlayerID() == 123 then print "hi" end
        end
    end
end
```
Takes about 5.7ms on my system.

Edit: I just realized the example you posted on dev.dota2 took 10ms and 8ms. So it's mostly my system. Could still become a probme though.

**Comment by Nostrademous** [comment]
Yeah, something is not efficient. Will have to seek it out.

**Comment by CsharpNoobDude** [comment]
I have a question:
I can not find the option "local bot script" in the lobby system any longer, did valve remove this option with one of the last patches? How can I play with these bots?

**Comment by Nostrademous** [comment]
https://github.com/Nostrademous/Dota2-FullOverwrite/wiki/Workflow-for-Debugging-Bots

**Comment by CsharpNoobDude** [comment]
I have a local lobby, but I can not choose local bot script for radiant, nor for dire.

**Comment by Nostrademous** [comment]
Did you copy/clone the git repo to the "bots" directory in as described in the wiki:

Create this folder (note: this assume default install location for Dota 2): C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\bots
Place your bot code in a special folder "Dota Game install Dir"\game\scripts\vscripts\bots (e.g C:\SteamLibrary\steamapps\common\dota 2 beta\game\dota\scripts\vscripts\bots)
Cd into "Dota Game install Dir"\game\scripts\vscripts
Clone directly into bots directory from the vscripts directory. git clone git@github.com:Nostrademous/Dota2-FullOverwrite.git bots

**Comment by Nostrademous** [comment]
Anyways, regarding Performance, I haven't tracked down exactly what is causing it... it doesn't seem like it's any of the modes/*.lua, nor the itemPurchase, nor the abilityUse... 

When I comment out the TeamThink() call (which considers all modes and then executes the Think() of the highest one) we obviously don't do anything but we have no performance issues. So it is somewhere in there...

**Comment by Nostrademous** [comment]
I won't be able to diagnose further until about 8 hrs from now.

**Comment by ByBurton** [comment]
Me neither: http://imgur.com/a/QmqPw

**Comment by Keithenneu** [comment]
Works for me. I don't have any workshop subscriptions active though.

**Comment by ByBurton** [comment]
I managed to get it running. But now, as soon as I start a bot match with your bots, it instantly crashes. Happens every time.
They pick normally, but after the picking screen.

**Comment by Nostrademous** [comment]
which branch?

**Comment by ByBurton** [comment]
then ew one ofc.

**Comment by CsharpNoobDude** [comment]
I was stupid :D. I forgot to create another folder, "bots" in vscripts :D

**Comment by Keithenneu** [comment]
Found it:
Calling `dofile` for about 10 times for every hero and every frame is _**not**_ something want to do.

```
ConsiderJungle in hero_think.lua:
[VScript] tryHeroSpecialMode took 0.1220703125 ms
[VScript] dofile jungling took 0.48828125 ms
[VScript] junglingMode:Desire(bot) took 0 ms
[VScript] ConsiderJungle took 0.732421875 ms
```
(It doesn't quite sum up, RealTime() might just not have the accuracy required for that kind of stuff (or I substracted the wrong value somewhere.. whatever))

`dofile` does - unlike require - not use a cached version of the file.
So we should either use require (feels odd, still), or implement some caching on our own. If you agree @Nostrademous, I'll give it a try.

**Comment by CsharpNoobDude** [comment]
I got ByBurtons problem now: It crashes as soon as the picking phase is over, during this loading screen that shows all dire / radiant heroes in a pose.

**Comment by Keithenneu** [comment]
Make sure you are on the branch `new_mode_format`. If the problem persists, please open a new issue. This one here is about perfomance issues, not crashes.

**Comment by Nostrademous** [comment]
@Keithenneu I have a cached solution I believe. Thank you for diagnosing that.

**Comment by Nostrademous** [comment]
pushed

**Comment by Keithenneu** [comment]
looks good.
