### ISSUE TITLE
What are You Working On?

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#171]
To avoid me working on the same thing "you" are working on, can you tell me what you are doing?

My plan is to start knocking out all the listed "bug" and "enhancements" that are not "spoken for" in the Issue Tracker, and adding new heroes when my brain gets fried.

**Comment by Keithenneu** [comment]
I'm working on gobal stuff, namely better push detection/response, better pushing. Also info about lanes that need help, be it to either survive or get a kill.
First goal is proper team wide pushing, like finding a lane to push, gathering in front of the base, and kill the tower.
I have some RL stuff coming up, so it won't be to soon.

**Comment by Nostrademous** [comment]
Cool, FYI, I started using the convention of bot.variableName to save bot-specific persistent information rather than setHeroVar() and getHeroVar(). It is "faster", and easier to access (you have it anywhere you call GetBot()). Eventually I will change out all our set/getHeroVar() to it, but not rushing that aspect.

**Comment by Nostrademous** [comment]
Checked in Legion Commander (didn't checkin the updated hero_selection.lua to not mess others up). It's a Jungling LC

**Comment by Nostrademous** [comment]
Checked in ported Venomancer semi-support

**Comment by Nostrademous** [comment]
In my next push I've added two new utility functions for team-fight logic:

InTeamFight(bot, range) - returns a list of allies that are in a "fight" mode within "range" from "bot", will include the unit asking the question is they are fighting already

GetScariestEnemy(bot, range) - returns the most dangerous enemy within "range" that is not already crowd controlled ( check utility.IsUnitCrowdControlled() for what it considers ) or "nil"

**Comment by Nostrademous** [comment]
I should have Spirit Breaker offlane build committed tonight.

**Comment by Nostrademous** [comment]
![image](https://cloud.githubusercontent.com/assets/1735956/24166058/6ef3e492-0e48-11e7-92af-383930febdb6.png)

Bots getting much stronger.
