### ISSUE TITLE
Help me help you guys!

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#18]
I read a few tutorials of how to do pull requests or stuff, but I don't get it.
I cloned it to my desktop. There is now a page "GitHub.com/ByBurton/Dota2-FullOverwrite".
But HOW can I put my changes I do in the desktop to yours, or to my browser thing?

**Comment by Nostrademous** [comment]
https://yangsu.github.io/pull-request-tutorial/

**Comment by Keithenneu** [comment]
I can't push branches to this repo. Did I misread something?
