### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#183]
We crash the game at times.... I have no idea where or why.... it sucks hunting these bugs.

No errors are emitted.

**Comment by Nostrademous** [comment]
Looks like it is in the jungling mode code

**Comment by Keithenneu** [comment]
can you provide a crash dump?

**Comment by Keithenneu** [comment]
when did you notice this crash for the first time?

**Comment by Nostrademous** [comment]
hm... won't let me insert a .zip here (even though it claims that's allowed)

**Comment by Nostrademous** [comment]
http://dev.dota2.com/showthread.php?t=278790&page=2&p=1423888#post1423888

**Comment by Nostrademous** [comment]
hm... hadn't had a crash in the last 4 play-throughs

**Comment by Keithenneu** [comment]
can't get the debugger to work on my laptop right now. I'll try againg on the weekend (tell me if it crashes again)

**Comment by Keithenneu** [comment]
i only saw somethin in the file about invalid ability flag: ..._not_attack_immune . not sure if thats related

**Comment by Nostrademous** [comment]
It crashed again twice since

**Comment by Nostrademous** [comment]
I believe the bug is tied to using items that are in backpack rather than main inventory.

**Comment by Nostrademous** [comment]
okay, I reverted back my repo to an old revision and bringing in back the changes to see what broke it...

so far it looks like a change in one of the modes (fight, defendlane, roam, evasion or pushlane)

**Comment by Keithenneu** [comment]
is there anything i can do to make a crash more likely?

**Comment by Nostrademous** [comment]
it's in fight or pushlane, most likely fight.

I mean, it happens for me almost every match. I just run a match with debugger attached (to capture the crash) at host_timescale 10.0

**Comment by Keithenneu** [comment]
ok, crash happened (freeze rather)

**Comment by Nostrademous** [comment]
just pushed a fix for the jungling crash

- running game #3 right now without any freeze/crash

**Comment by Nostrademous** [comment]
sigh, another crash still.....

**Comment by Nostrademous** [comment]
Ugh... still have a crash at times. Not sure what is causing it.

**Comment by Nostrademous** [comment]
okay, i think I figured it out

**Comment by Nostrademous** [comment]
Pushed a change that hopefully fixes all the crashes and freezes. Wasn't even our fault.

**Comment by Nostrademous** [comment]
Omg.... shoot me, it is still happening
