### ISSUE TITLE
defense is broken (again?)

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#184]
gotta fix this before I can move on to pushing.

**Comment by Nostrademous** [comment]
Yeah, I noticed it isn't working. Also noticed that using TPs is not working.

At least no more crashes.

**Comment by Nostrademous** [comment]
I'll fix TP use as soon as I verify that all my updates to Invoker (ported him to the same ability Use format as all the other heroes) is bug-free.

**Comment by Keithenneu** [comment]
Looks like the usage of enemy_data is the issue.
How is it supposed to work now? Without `enemy.Obj` I suppose?
`utils.ValidTarget(enemy)` crashes with `attempt to call method 'IsNull' (a nil value)` though.
All I need to get is the location. Valid target ensures that I can call :GetLocation(), right?

**Comment by Nostrademous** [comment]
yeah. enemy.Obj doesn't exist. It was causing all kinds of crashes with illusions in prior code.

**Comment by Keithenneu** [comment]
So enemy_data won't contain any handles, and I have to get them myself?

**Comment by Nostrademous** [comment]
yeah, just use GetUnitList() for that. enemy_data will contain info about enemies (index/based-of enemy Player IDs) such as what items they had last time we saw them, etc.

**Comment by Keithenneu** [comment]
K

**Comment by Keithenneu** [comment]
In defendlane.lua:
```
function X:OnStart(myBot)
    local bot = GetBot()
    bot.defendLane = true
end
```
However, bot.defendLane is also the mode implementation.
I'll just rename the variable for now. But getting a wider solution might become necessary.

**Comment by Nostrademous** [comment]
I think we just need a standardized naming convention so we don't trample on each other.

**Comment by Nostrademous** [comment]
about to push some changes to fix TP use - FYI

**Comment by Keithenneu** [comment]
PR #185 should hotfix defense.
Still needs lots of improvements.
