### ISSUE TITLE
[BUG] Attacking Barracks

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#186]
Our bots no longer right click barracks, no idea why.

They are fine on towers, shrines, and Ancient ( I believe ).

**Comment by Keithenneu** [comment]
I'll check it

**Comment by Nostrademous** [comment]
FYI - this was happening before your pull request, so not your fault.

**Comment by Keithenneu** [comment]
pushlane:Desire() only checks if there are towers nearby. So barracks are just pushed ins some edge cases.
I wouldn't bother fixing it, as I'm about to rewrite pushing determination anyway.

**Comment by Keithenneu** [comment]
Nvm, I'll fix it now. pushing looks somewhat fine for now. I'll work on global movement for now. This should improve push and defense further.

**Comment by Nostrademous** [comment]
Lane switching code is in decision.lua  ...  b/c I was lazy implementing it.

**Comment by Nostrademous** [comment]
btw... the pushlane:Desire() has other checks ... I still don't think it would work (for whatever reason) even if you added a rax check into Desire()

**Comment by Keithenneu** [comment]
yeah, mode is actually pushlane. I'm checking the think method right now.

**Comment by Keithenneu** [comment]
Ok. so bot:GetNearbyTowers() seems to return barracks as well. great.

**Comment by Nostrademous** [comment]
and what does bot:GetNearbyBarracks() return? I assume nothing?

**Comment by Keithenneu** [comment]
exactly. I'll file a bug on dev.dota2.com and split up the tower list by names for now.

**Comment by Keithenneu** [comment]
Had a fix. deleted it.

**Comment by Keithenneu** [comment]
aight, rewrote it. #187
