### ISSUE TITLE
Phantom assassin

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#189]
I saw your guys commit about PA. Her lasthitting sucks now, she wastes her daggers on full or nearly full health creeps now. I would change the if lane to this:
"if utils.ValidTarget(weakestCreep) and weakestCreepHealth <= weakestCreep:GetActualIncomingDamage(daggerDamage, DAMAGE_TYPE_PHYSICAL) then"
line 61

**Comment by Keithenneu** [comment]
Travel time might become an issue on higher levels

**Comment by Nostrademous** [comment]
I fixed that, just hadn't committed yet
