### ISSUE TITLE
Phantom Assassin items to buy

### ISSUE THREAD

**Issue by CsharpNoobDude** [Nostrademous/Dota2-FullOverwrite#194]
1 positive and 1 negative thing about the item_purchase list for pa:
+
That item build is one of my favourites, this is awesome. That aggressive PA you see nowadays should not work with bots very well I think.
-
treads_agility? Not treads_agi?

**Comment by Nostrademous** [comment]
Yeah, typo. Thanks, will be fixed in next checkin
