### ISSUE TITLE
Crystal maiden using frostbite on creeps

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#200]
On ranged creeps, siege too.

**Comment by Nostrademous** [comment]
It's probably a range check issue from the location of the "hard carry". She is allowed to use Frostbite on creeps so she can level and get gold when the carry is not nearby, but perhaps there are exception to the rule.

She tends to feed at start too much as well

**Comment by CsharpNoobDude** [comment]
Yes, but Drow too (and Invoker). Viper seems to be doing fine.
Another thing I noticed was, that if they try to help an ally, they seem to go in, no matter what. Sometimes suicide commando like, but later in the game it is actually quite effective.
Invoker seems to not use all of his skills, and sometimes even though he has enough mana for alacrity or whatever, he does not use it.
AoE spells of invoker are placed weirdly sometimes - one time invoker could hit 3 enemies with a meatball, but he managed to miss all of them, pretty impressive. Or the icewall. Really weird placements, but still better than my pubs - Invokers there only use alacrity, emp, chaos meteor and tornado, and sometimes cold snap.
But back to the feeding part. I think they should be more careful - Invoker especially. He has a level advantage - so he is longer dead.

**Comment by Nostrademous** [comment]
I feel there is a bug with Valve's FindAOELocation() API function which I use for many of the large AOE spells. I will try and ask ChrisC to look into it, because I know exactly what you are talking about.

**Comment by Riveon** [comment]
Just had a game where cm used frostbite on a creep instead of an enemy hero when she was being dived

**Comment by Nostrademous** [comment]
@Riveon thanks, I will fix that in next push... I was only checking 900 range for nearby enemies for that conditions... will be fixed to 1500.

**Comment by Riveon** [comment]
Strange, here she uses frostbite on a creep even though enemies are clearly in range: https://gfycat.com/WildUnawareAnophelesmosquito
