### ISSUE TITLE
Invoker not using his invisibilty when running

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#201]

**Comment by CsharpNoobDude** [comment]
I noticed that too. I actually think he is not using any ability when fleeing.
I didn't check his mana bar though. 
@ByBurton  Are you an Emma Watson fan?

**Comment by ByBurton** [comment]
Yes - she is awesome. She is such a strong personality, and I like that she stands up for equality. And that she also uses fair trade clothing. (Also she is beautiful :jealous:)

**Comment by CsharpNoobDude** [comment]
Well, I guess. 👍

**Comment by Nostrademous** [comment]
I think he does use his invis at times... just then instantly breaks it.

Issue I need to solve for this is a general issue for all heroes that are "invisible" - don't use items, abilities, etc or you break invisibility.

**Comment by CsharpNoobDude** [comment]
@Nostrademous  Now that you mention it, yeah. Bloodseeker with shadow blade, cm with her cloak...
