### ISSUE TITLE
Invoker  afk next to shrine

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#218]
Invoker went to shrine to heal, but stood next to it not activating it. 
Crystal maiden came to heal too, she activated it, healed up and went to lane again - Invoker still being afk.

**Comment by Nostrademous** [comment]
Should be fixed per Valve's fix. Let me know if it happens again.

**Comment by CsharpNoobDude** [comment]
@Nostrademous Well, I did.
Invoker was trying to use the middle shrine in the base. but did not use it. Cm came, used it, but invoker was still waiting there.
