### ISSUE TITLE
Invoker invoking spells but not using them

### ISSUE THREAD

**Issue by CsharpNoobDude** [Nostrademous/Dota2-FullOverwrite#219]
I saw Invoker correctly invoking the ghost walk while running, but not activating it, and thus died.
He had the mana for it. He actually had more than half of his mana pool.
Also I want to see fancy tornado - meatball - and the other aoe spell (all 3 elements).
And for early laning stage I would only use cold snap if invoker has a forge spirit.

**Comment by Nostrademous** [comment]
Found the bug with Ghost Walk - fixed.  a245291

For the other things - that's just a matter of tweaking desires appropriately, will get there.

**Comment by CsharpNoobDude** [comment]
@Nostrademous  Thank you.
