### ISSUE TITLE
Minor issues with Lina ability usage

### ISSUE THREAD

**Issue by Riveon** [Nostrademous/Dota2-FullOverwrite#220]
I noticed some issues with Lina (not sure how often they occur): 
- She used ult on an enemy hero when they were on 15 health (definitely secured the kill lol but a last hit would have been sufficient). 
- She used her LSA stun on a hero and then immediately used eul's on that hero, preventing the stun from having an impact.

**Comment by Nostrademous** [comment]
Fixed in 8a35d0c
