### ISSUE TITLE
CM switching lanes in laning phase

### ISSUE THREAD

**Issue by Riveon** [Nostrademous/Dota2-FullOverwrite#224]
Had a match where after killing CM she didn't come back to the radiant safelane, and instead joined the radiant offlane with Viper, leaving Sniper to fend for himself. Match ID is 3190327466 (don't know if replay will work for others or not though). This is the first match I've noticed anything like this happening though.

**Comment by Nostrademous** [comment]
That is allowed if the top lane was being pressured heavily

**Comment by Riveon** [comment]
Oh I see, that makes sense. I'm pretty sure it was being pressured so I'll close this.
