### ISSUE TITLE
It has nothing to do but?

### ISSUE THREAD

**Issue by raulnsuarez** [Nostrademous/Dota2-FullOverwrite#228]
@Nostrademous Hello, I live in Cuba and in my country the connections are through proxies and more proxies, so we can not use steam, but with other alternatives like SSE we can play offline on Local Network, even use scripts for the bots with RingGameCoordinator. Your work with the bots is much appreciated, and I want to try it, but I can not download it from steamworkshop, so you could please give me a link in MEGA, Mediafire, Zippyshare, etc to download the scripts and try them out. Thank you.

**Comment by walaoaaa1234** [comment]
`git clone` ?
or download as zip from github?

**Comment by raulnsuarez** [comment]
The zip files downloaded from github give me error and close dota 2, takes KBs; the steam workshop zip takes about 4 MB, maybe because it is more complete. They could provide me the most complete version to download as a zip and try it out.
