### ISSUE TITLE
Question About BotScripting, No Issues

### ISSUE THREAD

**Issue by TieConscious** [Nostrademous/Dota2-FullOverwrite#230]
Hi, I wanted to reach out about a question, but wasn't sure how else to contact you.
I'm currently working on a full overwrite of bots with a group, and we've run into an issue where certain heroes don't seem to work if they have certain skills leveled up. For example, Phantom Lancer eventually crashes the game if you level up his Q, but seems to do fine otherwise.
Is this an issue you've run into, and if so how did you solve it?
Thanks for your time.

**Comment by Nostrademous** [comment]
It's probably an issue with his illusions spawning from Q which are not treated properly so the AI system sends a command that's invalid (but not properly checked on the Valve engine side) to an illusion/clone and crashes the game.

Have you implemented a proper system for Minions, Illusions, Clones, and Doubles? They each are a different thing with different rules.

**Comment by TieConscious** [comment]
Thanks for the reply! I'll try that, but I also noticed the same thing happening with Phantom Assassin, Ursa, and Shadow Shaman.
I believe with Shadow Shaman it was his ult which stopped the game, though that could be a result of not controlling the snakes properly. I'm still at a loss as to why the other two would crash the game.
