### ISSUE TITLE
What IDE do you use?

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#24]
Hey guys,
I'm new to Lua and I usually use Visual Studio for coding,
however the Lua support for it isn't exactly what I'd call great..
What IDE do you use, is there one that offers as many comfortable features
sort of like Visual Studio or is there an extension I don't know about yet?

**Comment by Nostrademous** [comment]
I use Notepad++ for Lua.

**Comment by dralois** [comment]
I haven't thought of that one yet! I'll go and try that out, thanks!
