### ISSUE TITLE
Split up decision tree

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#25]
There should be separate files for the DetermineXYZ and DoXYZ functions, I think.

**Comment by dralois** [comment]
Export both function types or just one? It would be easier that way for sure though. The decision tree won't really shrink anymore anyway.

**Comment by Keithenneu** [comment]
One file for all Determine* function, one for all Do*. It's kinda hard to navigate through the decision tree as it is.

**Comment by Nostrademous** [comment]
I do not know LUA well enough to know how to do this while maintaining the necessary inheritance I need. You would need to make each file then be a "friend" (in C++ terms) of decision_tree... i don't think Lua can do that. Instead you can do "multiple-inheritance"; however, I have never tried it. What is in there now works, however feel welcome to implement it your way if you can get it to work.

**Comment by Nostrademous** [comment]
The re-organization of this file by dralois has made it much more usable, I'm closing this for now as while it is a larger file, I don't see any need for splitting it up currently.
