### ISSUE TITLE
Is there a HasRetreat function?

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#27]
If not where should I put it, I need a function like that for considering offensive/defensive item purchases.

**Comment by Nostrademous** [comment]
Not yet, but we need one. I would do by creating a global hero variable like I did in the case of bot_lina inside the DoInit().

local retreatAbility = npcBot:GetAbilityByName("PUT NAME HERE")
setHeroVar("HasRetreatAbility", retreatAbility)

So later wherever you want to check for it you can just do
local retreatAbility = getHeroVar("HasRetreatAbility")
if retreatAbility ~= nil and retreatAbility:IsFullyCastable() then
    npcBot:UseAbilityOnLocation(retreatAbility, loc)
end

Sorry if there is typos I'm on a cell phone

**Comment by dralois** [comment]
Alright I will do that, thanks!

**Comment by Nostrademous** [comment]
Perhaps Retreat should be replaced with Movement since  like you said it can be used defensively or offensively. So "HasMovementAbility". My suggestion.

 The reason this is a better way to do it in this case over creating a function is because a hero at Max only have one such ability and if he does we will need access to it anyways when we make this look up. So I feel this is more efficient .

**Comment by dralois** [comment]
True, Morphling's Waveform can be used to deal damage or to retreat while Invoker's Ghost Walk is mostly used to escape. Basically I want to write a function that tells me if a debuff item is needed or not.

**Comment by Nostrademous** [comment]
I will check in an implementation showing how I use it for Antimage's "Blink" under retreat conditions in a couple minutes, just waiting for him to get harassed to see it work before pushing change.

**Comment by Nostrademous** [comment]
pushed... needed to change DoInit slightly since I realized it wasn't working properly for levelling. But fixed now.

**Comment by dralois** [comment]
Alright I'll sync. Good work!
