### ISSUE TITLE
Items need to be put in tables sort of like with heroes in role.lua

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#31]
That makes it unnecessary to list every single part of an item instead of the actual item.
Should return a table with the components.

**Comment by ByBurton** [comment]
Well, but sometimes you want to buy a part of the item first, and then buy other stuff and then finish it later. I do not think that is going to work most of the time.
E.g.: Starting items. 2 iron branches, tango, clarity. ->bottle ->circlet -> magic stick
If you would have called magic wand from a table you would buy this after the bottle: 2 branches, circlet, magic stick.

**Comment by Nostrademous** [comment]
There are ways to do this. But honestly and eventually we will need items arranged into cause/effect tables so you can decide in real time what items to buy in response to the opposition.

**Comment by pbenologa** [comment]
I made a table file with all the items. You can check it here. https://github.com/pbenologa/Dota-2-Bot-Files/blob/master/items_recipes.lua. Hope this can be somewhat helpful.

**Comment by dralois** [comment]
The table looks good, I'll use and modify it if that's alright. I'll try to think of a solution to the buy in parts problem, I'm sure there's a way to handle that. Right now you can't modify purchase order at all anyway, so buying items in parts is probably something for the future, beeing able to choose items based on the current state of a game is more important imo.

**Comment by Keithenneu** [comment]
You could make it look like this:
buy brown boots
buy power threads (automatically buys missing parts, aka gloves and belt)

Disassembling and selling is still needed though.

With more sophisticated buying methods, we also want to prevent unintended assembling of items (like brown boots for threads, ring of protection and regen for vlads -> wild tranquils appear).

I'll try to think of a method that covers all the things discussed. Won't guarantee any results though :D

**Comment by dralois** [comment]
That sounds like a great idea, I can simply compare my inventory to the item parts of what I want to buy and only buy what I don't already have. I'm making progress with my reactive item purchase code, will still take some time though since I can't work on it very often this week.

**Comment by Keithenneu** [comment]
Just checking the inventory might not be enough. Make sure to look at the courier and stash as well.
(Or save what you bought already.)

**Comment by dralois** [comment]
Good catch. I'll save what I bought and compare that instead, that should deal with the courier and stash problem.

**Comment by dralois** [comment]
But wait a second.. You don't HAVE to use the item table, you can of course also add single items. Then you could just add brown boots, bottle, rest. So no need for saving what we bought already?

**Comment by Keithenneu** [comment]
The best I can think of, is to provide a "value" value (screw english) for each item. This can be hardcoded (very low for tangos and branches, very high for Butterfly etc.). But also be calculated by the framework, depending on enemies, playstyle and so on.
If we don't have anymore space for better items, we sell the least valued.
Items like gem, wards, smoke, tp etc should have rather high values, or should just be protected from selling.
Items like tp, wards could also be kept in the backpack. I think hardcoding these cases should be fine.

**Comment by Keithenneu** [comment]
The overhead of storing items shouldn't be to big. Especially since we don't need to touch it often (Just whenever we buy a new item).

**Comment by dralois** [comment]
I like the item value idea. Right now in the decision process only heroes that are not core buy support items. The next step is to calculate what damage the enemy mostly does, how much disable/ how many silences the enemy has and how many of them have true strike. I'll add that value parameter to the item table I think, needs to be balanced out of course.

**Comment by Keithenneu** [comment]
That's the nice thing about these values though. It's easy to provide good enough values for now, but the can calculated to perfection later on.

**Comment by dralois** [comment]
I just use the item cost for now with a few exceptions. This can of course be customized later.

**Comment by dralois** [comment]
@pbenologa's table is uploaded on my fork, unfinished generic item purchase is also up.

**Comment by Nostrademous** [comment]
Are you going to submit a pull request for it to merge it back in or you waiting to finish it up more first?

**Comment by dralois** [comment]
I will as soon as I know its working since I don't have access to dota right now.
There are also still quite a few parts that aren't nearly finished yet.

**Comment by Nostrademous** [comment]
just an FYI - I'm almost done implementing a method for going to Secret Shop to purchase items from there if sNextItem happens to only be available in Secret Shop.... this will lead to some code migration into your purchase Think

**Comment by dralois** [comment]
Very nice, I am currently changing a couple of things, then I'll test them and if everything works as intended so far I'll submit a pull request.

**Comment by Nostrademous** [comment]
Pushed pathing and buying stuff from SECRET SHOP... 

However, we still don't have side-shop purchasing coded and technically we should check if an item is available at secret or side or both and find closest one and then path there.
