### ISSUE TITLE
Sell/Drop Items

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#34]
Need to implement some form of item recycling when they are no longer needed, like ironwood branches.....

**Comment by dralois** [comment]
Side question: Are there ways to plant branches and eat them with tangoes? Would be something that could be very important to implement as well.

**Comment by Keithenneu** [comment]
"branch" occurs in item buy lists only. So it's most likely not implemented.

**Comment by Nostrademous** [comment]
I think "Action_UseAbilityOnLocation()" should work for items like ironwood. The question is if GetNearbyTrees() will return for a tree created by ironwood and if there is a way to differentiate an ironwood tree from a normal tree.

**Comment by pbenologa** [comment]
Is it possible to use "Action_UseAbilityOnLocation()" on "tango" then use the passed location to plant the tree onto the required location for using "tango"?
