### ISSUE TITLE
Backpack 

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#35]
The bots need to understand how to use the backpack feature - I see them running around with a complete Shadow blade, power treads etc. in their backpack.
The other issue is already mentioned (they do not sell items).
I understand that this is still heavily under development, but I think that should be easy to implement? Idk.
Also I want to mention it here and not open a new threat - as soon as someone makes a PA bot, I hope you gonna make her lasthit with daggers if she is outzoned, too much under harassment. 
But holy shit, that bloodseeker bot and Lina are actually impressive already. Good job guys!
And holy shit you worked a lot on this today.

**Comment by Nostrademous** [comment]
really? I only had 2 hour today as it's a holiday in the US and I was home with both kids and so could only work while they napped around lunch time... all the jungle stuff is from another contributors with minor edits by me.

**Comment by Nostrademous** [comment]
Also, yes.. about the backpack. I have code to move items from stash into inventory and then into backpack based on free space. However, no code to move "better" items from backpack into inventory. I'm hoping some of it is fixed wen I implement Drop/Sell code

**Comment by Keithenneu** [comment]
Yeah, I was once again surprised by how much time I need for so little code :D
But it's bloodseeker, so I'm happy I did it.
Currently he's just afk farming till the game ends (2k mmr Kappa). I think I'll make him a little more active, but have to focus on exams soon.

**Comment by ByBurton** [comment]
Keithenneu, thanks for all the support and stuff. This is just awesome, this whole stuff here. All that code today... dafuq..

**Comment by Nostrademous** [comment]
Implemented swapping items from backpack to inventory if inventory has ironwood branches - still need to do item selling/dropping code to really fix the issue

**Comment by dralois** [comment]
I'm working on the selling part, however bots aren't making use of the backpack yet. I need to think about what items we want to put in it (e.g. tp if we can buy something in the sideshop, parts if we can buy something better..).

**Comment by Nostrademous** [comment]
Bots should put items in backpack if there is space and they are in the Fountain area. That code is in. They don't prioritize what items to put if there is not enough space for them all. They will swap ironwood branches out of inventory and into backpack, but that's all I coded so far.

**Comment by dralois** [comment]
Hmm I guess "advanced" backpack usage has to be implemented after side shop usage anyway

**Comment by Nostrademous** [comment]
Side Shop usage is in.

**Comment by Nostrademous** [comment]
Swapping from Backpack to Inventory and vice-versa is in. Primarily I coded the swapping of TPs and Tome of Knowledge (will need to add other consumable items probably in the future). Closing this for now as it is too broad a topic at this point.
