### ISSUE TITLE
Basic Roaming

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#36]
I'd like to build some basic roaming, to allow Bloodseeker to get more active during the laning phase.
What I want to do:
- during jungling, try to stay close to lanes that might need help, or have good kill potential
- once we have ult (or whatever we need to secure a kill): go to well positioned (pulled) lanes and kill.

Are there any functions yet, to get data about lanes?:
- potential of getting a kill (having stuns and damage; lane is pulled)
- potential of getting killed (enemy has stuns, damage; lane is pushed or enemy can dive)
- position of lane between t1 towers

This should yield good results and not be to hard to implement for now. Later on, this should be integrated with some overall tactic considerations and fighting logic.

**Comment by Nostrademous** [comment]
Some of this is in already, although brittle. I need to create a wiki explaining the framework so it's easier for others to contribute.
It will be here: https://github.com/Nostrademous/Dota2-FullOverwrite/wiki

**Comment by Keithenneu** [comment]
Once I've chosen a target, how do I attack it? Including ult usage, and getting allies to help.

**Comment by Nostrademous** [comment]
do...

if self:HasAction(ACTION_FIGHT) == false then
    print(utils.GetHeroName(bot), " - Fighting ", utils.GetHeroName(target))
    self:AddAction(ACTION_FIGHT)
    self:setHeroVar("Target", target)
end

**Comment by Nostrademous** [comment]
I assume that's what you are asking..

**Comment by Keithenneu** [comment]
Currently im adding ACTION_ATTACK, and set heroVar `Target` to my chosen target.
The target is cleared by something just split seconds later though.

**Comment by Nostrademous** [comment]
If you set ACTION_FIGHT and set setHeroVar("Target", target) like you say you are... then the X:DoFight() in decision_tree.lua will be invoked

it's possible you are picking a target stand near their tower (within 750 units)  so the bot kick into the GetEstimatedDamageToTarget() and thinks it can do 0 dmg probably since it is not "close" to the target

**Comment by Nostrademous** [comment]
I would not call ACTION_FIGHT until you are near target... push ACTION_ROAM onto action stack and use X:DoRoam() instead to roam to the target and then invoke "ACTION_FIGHT" once you are there

**Comment by Keithenneu** [comment]
That's what im doing actually.
Just Target being cleared breaks it.

**Comment by Nostrademous** [comment]
Is the target of roam standing under tower?

**Comment by Keithenneu** [comment]
Nope.
I'll try to find the exact function which invokes setHeroVar("Target", nil). That'll tell us more.

**Comment by Nostrademous** [comment]
if myDmgToTarget > target:GetHealth() and towerDmgToMe < (bot:GetHealth() + 100) then
				--print(utils.GetHeroName(bot), " - we are tower diving for the kill")
				if target:IsAttackImmune() or (bot:GetLastAttackTime() + bot:GetSecondsPerAttack()) > GameTime() then
					bot:Action_MoveToUnit(target)
				else
					bot:Action_AttackUnit(target, false)
				end
				return true
			else
				self:RemoveAction(ACTION_FIGHT)
				self:setHeroVar("Target", nil)
				return false
			end

**Comment by Nostrademous** [comment]
it probably doesn't think you can do enough damage to kill the target so it says don't fight and nil the "Target"

**Comment by Nostrademous** [comment]
b/c it doesn't consider the damage from any Allies next to you... just your solo damage

**Comment by Keithenneu** [comment]
I'm still in ACTION_ROAMING though

**Comment by Nostrademous** [comment]
is the code checked in, in your fork?

**Comment by Keithenneu** [comment]
Now it is.

**Comment by Nostrademous** [comment]
lines 491 or 498 in decision_tree.lua probably doing it since "ShouldIFight()" is evaluated before ShouldIRoam

**Comment by Keithenneu** [comment]
It is. just checked it.

**Comment by Keithenneu** [comment]
no wait.

**Comment by Keithenneu** [comment]
It's line 466. The utils function resets the target, if none is found.

**Comment by Nostrademous** [comment]
okay, that clear is probably unnecessary in utils.FindTarget()

**Comment by Nostrademous** [comment]
but fixing that I think you will then have it still cleared by 491 or MOST LIKELY 498 in decision_tree

**Comment by Keithenneu** [comment]
So I just use GankTarget, and Target as soon as I'm close to it and switch do Action_Fight

**Comment by Nostrademous** [comment]
right... best way to do that

however, you might find that you still don't attack until we add code for ally support since the code will probably estimate that you are not doing enough damage over the time (solo - since it doesn't consider allies for now) to get a kill and then stop fighting to fallback to last-hitting/laning

**Comment by Nostrademous** [comment]
another way to fix it is for me to finish implementing "harassment" code as part of Laning so when you "roam" into a lane the code will know you are not a "Core" that requires last hits and instead focus you on harassment and creep deny

**Comment by Keithenneu** [comment]
Thats true for full time roamers, but as a Jungler, I just want to kill someone and go back to farming.
I'm not sure how to divide these classes of junglers. Maybe it's acutally ganking what I'm doing. Just like midlaners would.
There are however junglers, who are something in between, like Chen (or Enigma, if times are hard.)

**Comment by Keithenneu** [comment]
It just feels hard to put all this in a state machine.

**Comment by Nostrademous** [comment]
don't get bogged down on that issue b/c:

* I can always fix the state machine and help out 
* eventually the state machine will be thrown out and replaced with an intelligent planner I will put in

**Comment by Keithenneu** [comment]
It's kinda working now :)
He's still a little suicidal, but that's just fine tuning.

**Comment by Nostrademous** [comment]
Done.
