### ISSUE TITLE
AmISafe returns 1 (enemy hero) while jungling far away from any enemy

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#37]
I guess something is off with the calculation. Not sure though.

It's the line
`(bot:GetHealth() < (bot:GetMaxHealth()*0.17*(nEn-nAl+1) + nTo*110))`
And it happened at about 34% life.

it also returns 1 if we're already retreating to fountain, making it impossible to differentiate these cases.

**Comment by Keithenneu** [comment]
It's the line
(bot:GetHealth() < (bot:GetMaxHealth()*0.17*(nEn-nAl+1) + nTo*110))
And it happened at about 34% life.

**Comment by Keithenneu** [comment]
it also returns 1 if we're already retreating to fountain, making it impossible to differentiate these cases.

**Comment by Nostrademous** [comment]
There are 3 retreat cases:

1 - the major retreat case which uses the calculation above and falls through to retreat_generic.Think()
2 - we are hit by tower and just want to move back a bit
3 - we are hit by creeps and just want to move back a LITTLE bit

that line (part of OR clause) is a left over from before I was differentiating creep and tower dmg separately, can be removed

**Comment by Nostrademous** [comment]
I am removing that portion of the line in the next checkin

**Comment by Nostrademous** [comment]
pushed...

**Comment by Keithenneu** [comment]
Thanks :)

**Comment by Keithenneu** [comment]
Still backs up when on low life. For now, I disabled the enemy part, if there are no enemies around.
Can I included it in a pull request like this?

**Comment by Nostrademous** [comment]
Submit it and I will look at it. Perhaps AmISafe should take an argument with thresholds for mana and health so more customizable

**Comment by Keithenneu** [comment]
should be up in a few minutes. I'm currently testing it by buying 12 calrity as starting items, to make sure bloodseeker gets low enough to retreat. What a hero.

**Comment by Nostrademous** [comment]
Made some changes to not do the "health" check if JUNGLING

**Comment by Nostrademous** [comment]
Looks fixed to me

**Comment by Keithenneu** [comment]
Yeah, this particular issue seems fixed. Retreating still doesn't work for me though, and I have no idea why.

**Comment by Keithenneu** [comment]
What's the difference between HeroVar IsRetreating  and ACTION_RETREATING? This seems to be the cause

**Comment by Nostrademous** [comment]
What do you mean by "not work for you"... my Bloodseeker runs away when REALLY low life and goes to fountain (although sometimes he stops at another camp first ... sees that's it is empty and then heads home). It is the same code for both of us (unless you have uncommited changes in your branch).

**Comment by Keithenneu** [comment]
He doesn't run straight to fountain, but turns back to the camp, or checks other camps first.
He should just run home, without carin about anything. (Could be implemented later on, but it's not intended at the moment)

**Comment by dralois** [comment]
Yesterday during testing Anti Mage never used regen items and instead went back to fountain, is that normal? Might be relevant.

**Comment by Nostrademous** [comment]
That's fixed as of last night... I accidentally move "UseItem()" code to be AFTER the check for RETREAT... so they would retreat and then return out of Think(). I fixed it late last night by moving ConsiderItemUse() above AmISafe() which triggers retreat.

**Comment by dralois** [comment]
I didn't use that update, but that sounds a lot like what happened there. 
I'll see if the behaviour changed later.

**Comment by Keithenneu** [comment]
I didn't care to much about how this action stack works at all. So I guess I messed something up regarding that one.

**Comment by Nostrademous** [comment]
I am planning on putting it on the project's wiki to explain how it works... but I have real-life work commitments with deadlines of this friday for a lot of work so not sure when I get to it.

**Comment by Nostrademous** [comment]
I think I figured out why this happens... testing a fix now.

**Comment by Nostrademous** [comment]
fixed and pushed

**Comment by Keithenneu** [comment]
Thanks a lot!
