### ISSUE TITLE
Code won't compile

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#39]
And I can't figure out why.. Is there a good way to debug that? A logfile that I can look into or something? It probably is just something little but my IDE doesn't show me those probably obvious mistakes, in fact it doesn't tell me anything :(

**Comment by Nostrademous** [comment]
Does it crash DOTA2?

**Comment by Nostrademous** [comment]
If it does crash dota2 then you need to enable console debugging and dumping to file.
Change the launch options in Steam for Dota2 under to include "-condebug"
To do this: Right Click on Dota 2 in Steam Library -> Properties -> General Tab should have a buttone for SET LAUNCH OPTIONS..." type the above in there.

The files will be dumped to: (on Windows)
C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota

And named something like "console.<NUMBER>.log" (sort by Date modified to get latest one)

**Comment by Keithenneu** [comment]
Atom with linter and lua linter displays syntax errors. And keeps whitespaces clean. And stuff..

**Comment by dralois** [comment]
Cool, I'll give it a shot! Maybe it'll find the bug for me :')

**Comment by dralois** [comment]
Hmm I cant find it right now, I'll continue looking tomorrow,

**Comment by dralois** [comment]
Alright I looked into it with Atom and found a few mistakes and bugs, it doesnt crash anymore and seems to sort of work. I can however not use the console command dota_bot_reload_scrips, that crashes the game..

**Comment by Nostrademous** [comment]
Yep, it does. I reported that a long time ago to the devs

**Comment by dralois** [comment]
Ah okay, so not only my problem. Hope they fix that soon, would be very nice to have that command..
