### ISSUE TITLE
Make wiki editable?

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#45]
Is that possible? I would like to add how to implement a item_purchase_SomeNewBot since that works a little bit different now.

**Comment by Nostrademous** [comment]
I can make the Wiki public editable or only to "collaborators". For now in the name of security I sent you an invite to be a collaborator and once you accept you should be able to edit the wiki

**Comment by dralois** [comment]
Yeah its better that way for sure. Thank you!
