### ISSUE TITLE
How do I get all visible enemy Heroes?

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#46]
Is there a way of getting all visible enemy heroes? GetNearbyHero doesn't work on big ranges. I can't gank with just 1500 EyeRange.

**Comment by Keithenneu** [comment]
Found something in the PubSim Code.

**Comment by Nostrademous** [comment]
As of January 12, 2017 according to Valve you can do this:

* Added GetUnitList() global bot script function for returning a list of the specified unit types.
* Added UNIT_LIST_ALL, UNIT_LIST_ALLIES, UNIT_LIST_ALLIED_HEROES, UNIT_LIST_ALLIED_CREEPS, UNIT_LIST_ENEMIES, UNIT_LIST_ENEMY_HEROES, UNIT_LIST_ENEMY_CREEPS, and UNIT_LIST_NEUTRAL_CREEPS global bot script constants.

So I assume GetUnitList(UNIT_LIST_ENEMY_HEROES)

**Comment by Nostrademous** [comment]
There is another way (which might be less or more efficient which exists in our enemy_data.lua

**Comment by Nostrademous** [comment]
Which ever way you use... when you do get a handle to an enemy you can then do a check to see if it is visible by checking if "enemy:GetHealth()" returns -1. It will return a real value if they are visible for any reason (our creep see them, our wards see them, our heroes see them, bloodseeker passive sees them, etc.).

Be weary of the unit-scoped: IsInvisible() b/c it returns true/false based if that unit thinks it is invisible... for example it will return "true" when they used "shadow blade" and our under its effect, even if they are dusted or you have true sight gem and standing next to them.

**Comment by dralois** [comment]
Is there a way to determine how many heroes with invisibility are in the enemy team? If not we should probably add a HeroVar "HasInvisibilty" or something like that.
