### ISSUE TITLE
Fix Bloodseeker Retreat to not have Hardcoded Health Threshold

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#49]
Currently BS will retreat if he falls below the maximum of (15% health, 100 hp). What sometimes happens is that he is 1 more hit away from killing a remaining neutral creep that would have healed him up, but he hits the threshold and start running away... this is dumb. We should add code to check if he can kill something and heal up before getting killed using GetEstimateDamage()

**Comment by pbenologa** [comment]
I made a code regarding this not sure if it's a good approach. Basically after the check if the bot's health is below the health threshold i added another condition that checks if his estimated damage is less than the current health of his target and if the bloodrage heal from target + bloodseeker's health is less than the health threshold.

**Comment by Nostrademous** [comment]
Follow that up with the target:GetActualDamage(estimageDamage, DAMAGE_TYPE_PHYSICAL) which will help get a real damage number based on armor of target. And should be good.

**Comment by pbenologa** [comment]
Thanks!. Will publish it once the pull request conflict is fixed.
