### ISSUE TITLE
Can't access global hero data

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#50]
So when I try to get values from global hero data that doesn't work,
it always returns a nil value. The first time an item purchase script is called it calls an init function,
that init functions needs to be able to access the role a hero has. However when I try to get the role
it doesn't do anything.. I still don't fully understand how data is stored in global hero data and who can access is, so that might be part of why it doesn't work.

**Comment by Nostrademous** [comment]
I can fix that later tonight. It is a race condition issue

**Comment by Nostrademous** [comment]
so the problem is that your "purchase" code is beating my "hero creation and initialization" code to the punch. Do you have the following at the start of your think function before you do anything:

if ( GetGameState() ~= GAME_STATE_GAME_IN_PROGRESS and GetGameState() ~= GAME_STATE_PRE_GAME ) then return end

**Comment by Nostrademous** [comment]
hopefully fixed in last push providing above comment.

**Comment by dralois** [comment]
Is it even possible for that class to access the global hero data? Is it saved accross all scripts that want to access it or do you have to fill it every single time manually? I ask because I had the same problem (returns nil) with enemy data, more specifically trying to get the handle to an enemy that's saved.

**Comment by dralois** [comment]
The return statement is in my Think() though, I tried to call the Init() both after that return and whenever ItemPurchaseThink is called for the first time.

**Comment by Nostrademous** [comment]
You have access to global hero data - just pushed working code with it implemented in item_purchase_generic_test.lua.

I think why it wasn't working previously is that the inheritance code for item purchase of heroes was very broken b/c of how it works in Lua. I can explain to you what was occurring and how it was fixed but you see it in your fork with the conflicts you have.

**Comment by Nostrademous** [comment]
Stay away from enemy_data for now.. nothing is populating it at the moment and there are kinks to work out with it... Valve released an easier way to access it which will be more efficient then my LUA implementation since theirs is implemented in C++ backend.

**Comment by dralois** [comment]
Okay I'll look into it. Going to change fetching enemies using Valve functions for now. Thanks for fixing it though!

**Comment by Nostrademous** [comment]
Just be weary of how you use the Valve functions... they said themselves that if you over-use them you will have drastic performance issues. I would make sure you throttle the frequency of use.

Actually, I want to implement and fix the enemy_data.lua to use them safely and atomically. Also, I think Keithenneu is needed that info too. We might be replicating the work between all of us.

**Comment by dralois** [comment]
Hm yeah that would be wasted time, I'll just fix everything up to buying extension items, since that's the first time I would have to use enemy information. Btw why did you not make local values for starting items, core items etc.?

**Comment by Nostrademous** [comment]
They are local in the hero's class (like item_purchase_antimage.lua, or item_purchase_viper.lua). Not sure what you mean?

**Comment by dralois** [comment]
Oh yeah my bad, they are not anymore in my fork (since there can be multiple different purchasing paths for carry, support etc.). I assume I have to make a local version of those just like you did with BoughtItems and PurchaseOrder as well?

**Comment by Nostrademous** [comment]
Yes, otherwise any other bot that inherits from the item_purchasing_generic_test.lua will over-write them as soon as they are created.

**Comment by dralois** [comment]
Okay, I did that and also merged the versions together. Once I tested everything and know if it works I'll send a pull request. If the global hero data thing is fixed it should though.
