### ISSUE TITLE
Item Purchase Generic Test - Piecemeal Purchasing

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#52]
Wiki says you will consider piece-wise purchasing and track what you already bought to help determine if you need to purchase an item you might already have. This is not the case.

I don't see self.BoughtItems being really used anywhere to check... just populated

**Comment by dralois** [comment]
Yep that's part of the next update, I figured I would include it in the wiki already.
I'll send a pull request later today if everything works as intended.
