### ISSUE TITLE
Global Enemy Hero Information

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#53]
I think all 3 of us are needing this information.

I want to make sure all 3 of us are not implementing different solutions (or even the same solution and wasting time).

Who is doing anything with this?

I assume we will be basically working using the enemy_data.lua but re-writing chunks of it using the new Valve provided APIs of:
* Added GetUnitList() global bot script function for returning a list of the specified unit types.
* Added UNIT_LIST_ALL, UNIT_LIST_ALLIES, UNIT_LIST_ALLIED_HEROES, UNIT_LIST_ALLIED_CREEPS, UNIT_LIST_ENEMIES, UNIT_LIST_ENEMY_HEROES, UNIT_LIST_ENEMY_CREEPS, and UNIT_LIST_NEUTRAL_CREEPS global bot script constants.
* GetLastSeenLocation() and GetTimeSinceLastSeen()

**Comment by dralois** [comment]
Like mentioned in the other issue I'll try to get the item purchasing to work like it want it to up until the first point where I need information about enemies. If we don't have an improved version by that time I'll try my best to help improve it, but until then it will stay untouched.

**Comment by dralois** [comment]
Will we have to rewrite parts of utility.lua as well? There's a lot of functions that don't use those new API features but the (older?) version of it. Is there a benefit of replacing that?

**Comment by Keithenneu** [comment]
Currently I'm just doing very basic stuff based on heroes that are visible on the map, using GetUnitList().
I won't need/write more than this anytime soon.

**Comment by Nostrademous** [comment]
Okay - FYI - Valve's implementation is currently broken partially apparently (until next update)

http://dev.dota2.com/showthread.php?t=276309

**Comment by Keithenneu** [comment]
Damnit, I used this as a feature :D
Will be easy to fix though, so thanks for the warning.

**Comment by dralois** [comment]
I'll keep it in mind 😃

**Comment by Nostrademous** [comment]
FYI - the reason it was breaking before and erroring for you dralois is b/c both the enemy_data.lua declared a global table called "X" and items.lua did. And Items was brought in second so it was over-writing the enemy_data global X.

I made them both local now and renamed enemy_data to use ED as the top level table just in case. Problem went away.

**Comment by dralois** [comment]
Wait.. so that means if you declare something global in two different files and load both of them in another it only works if those two things have different names? Kinda weird but I'll keep that in mind. Lua has some interesting aspects to it apparently.

**Comment by dralois** [comment]
Well I guess it does make sense if I think of a lua file like a module, the only weird part is how oop works.

**Comment by Keithenneu** [comment]
AFAIK You can control this global stuff by keeping your modules Environment in a table, using get- and setfenv.

**Comment by Nostrademous** [comment]
Nothing technically needs to be global. Just realize Lua is basically treating everything like a pointer.

For example is you do:
local a = { [1] = "abc" }

local b = a
local c = a

c[1] = "xyz"

If you print b now it will show "xyz" too

**Comment by dralois** [comment]
Ah okay, I did not know that yet. Just something I have to remember.

**Comment by Nostrademous** [comment]
About to check in a new implementation... doesn't have everything we need yet but I found that storing the "enemy" object provided by Valve is bad... as it is "transient". Meaning they modify it based on our team's vision. I want the "enemy_data" to be complete data from last time I saw the hero.... so I implemented that.

dralois - you will have to change item purchasing for Buying Extensions
