### ISSUE TITLE
Update our code

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#55]
http://dev.dota2.com/showthread.php?t=276342

**Comment by dralois** [comment]
That's a pretty cool update, finally script reloading.. Is there a way to tell if a courier is flying or not now?

**Comment by Nostrademous** [comment]
That's what I asked in their forum. I wonder if you just can't buy the flying upgrade once you bought it the first time and if we could use that as a test value.

**Comment by dralois** [comment]
That would make the most sense, but couldn't you just buy the item twice or is there a different way that disables the upgrade after buying it?

**Comment by Keithenneu** [comment]
You can buy multiple flying couriers in a real game. Why not in bot games?

**Comment by dralois** [comment]
Exactly, but we don't want them to buy multiple ones I assume :smile:

**Comment by Nostrademous** [comment]
actually, with AI/scripting the control of multiple units is very easy ... so having 5 couriers and properly controlling them would be much easier than for a human that can only pay attention to so many things at once

**Comment by dralois** [comment]
But muh efficiency

**Comment by Nostrademous** [comment]
Pushed a change that addresses all the patch note changes... COURIERS WON'T DELIVER ITEMS until the fix something they broke in the next update.

Items will be transferred to a courier though, just not delivered (except for CM who is not our bot, but default bot)
