### ISSUE TITLE
GetItemCost error

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#56]
I'm getting a lot of
`[VScript] GetItemCost parameter 1: expected cstring but got hscript.`
starting at about 3:30 into the game.
Is this a known issue?

**Comment by dralois** [comment]
Yeah, I pushed an (untested) update to my fork, I'll test it later today. You can "fix" it by commenting out ConsiderSellingItems

**Comment by Keithenneu** [comment]
I'm not using your fork, so I shouldn't get the error just because of your push.

I'll find it out..

**Comment by dralois** [comment]
Yeah I just thought I know what error you're talking about but I meant something else (which I think I fixed). Do you use item_purchase_generic_test or generic_item_purchase?

**Comment by Keithenneu** [comment]
stack trace says item_purchase_generic_test called from viper.
I'll have the item name in a few minutes.

**Comment by dralois** [comment]
Hmm okay, I'm very curious what's causing problems now.

**Comment by Keithenneu** [comment]
Oh, well, it's not a string, it's a table.
I'll print the contents in the next game (~10minutes)

**Comment by dralois** [comment]
Hmm maybe it's not getting the components correctly. I assume it's the ring of aquila which consists of two tables. Those tables are then being handed over to GetItemCost and it crashes. I'll fix that real quick.

**Comment by Nostrademous** [comment]
Yes, you only deconstruct a table 1 time... not nested tables

**Comment by dralois** [comment]
Gotta be it. Fixing it now.

**Comment by Keithenneu** [comment]
[VScript] 1	item_branches
[VScript] 2	item_chainmail
[VScript] 3	item_recipe_buckler
[VScript] GetItemCost parameter 1: expected cstring but got hscript.

Looks like meka :)

**Comment by dralois** [comment]
Same problem though, chainmail should be a table

**Comment by Keithenneu** [comment]
I also get a bunch of Action_CourierDeliver being nil. Anyone working on this?

**Comment by dralois** [comment]
Do you know if Viper bought or attempted to buy RoA first?

**Comment by Keithenneu** [comment]
she has power treads completed, nothing else.

**Comment by Nostrademous** [comment]
I am fixing Courier... they changed the API

**Comment by Nostrademous** [comment]
they changed it... and broke it, courier might not work till next update

**Comment by Keithenneu** [comment]
oh, ok.

**Comment by dralois** [comment]
hm yeah she buys treads first and should then buy RoA, that's why I was wondering

**Comment by Nostrademous** [comment]
HERE: [https://goo.gl/nPZx3Y](https://goo.gl/nPZx3Y)

Wrote a flatten function that recurses...

you still have a bug in Veil of Discord.... need an X[] around the second null talisman

**Comment by Nostrademous** [comment]
Also curious why you wrote things like this:

X["item_necronomicon_1"] = { "item_staff_of_wizardry", "item_belt_of_strength", "item_recipe_necronomicon" }

X["item_necronomicon_2"] = { "item_staff_of_wizardry", "item_belt_of_strength", "item_recipe_necronomicon", "item_recipe_necronomicon" }

X["item_necronomicon_3"] = { "item_staff_of_wizardry", "item_belt_of_strength", "item_recipe_necronomicon", "item_recipe_necronomicon", "item_recipe_necronomicon" }

Instead of this:

X["item_necronomicon_1"] = { "item_staff_of_wizardry", "item_belt_of_strength", "item_recipe_necronomicon" }

X["item_necronomicon_2"] = { X["item_necronomicon_1"], "item_recipe_necronomicon" }

X["item_necronomicon_3"] = { X["item_necronomicon_2"], "item_recipe_necronomicon" }

**Comment by dralois** [comment]
I actually did not write this, it's from another user. I think he did the same thing for Dagon as well.

**Comment by Nostrademous** [comment]
Do you want me to fix it.... or are you fixing it? I want to try and avoid merge conflicts

**Comment by dralois** [comment]
I'll fix that and go though the item list to check for more inconsistencies

**Comment by Nostrademous** [comment]
just implement the "flatten()" code I posted in that link... and it will recursively flatten the table to raw items and then pass that to the "for _, p in pairs()" each time

**Comment by dralois** [comment]
Yup I'll just copy it in

**Comment by dralois** [comment]
It seems like it doesn't work for dagon, the null talisman is not returned

**Comment by dralois** [comment]
Apparently it only works if the table for the null talisman is being created first.

**Comment by Nostrademous** [comment]
That make sense... so alphabetizing it was a bad idea

**Comment by dralois** [comment]
Yep. Needs to be rebuilt, I'll do that as well.

**Comment by dralois** [comment]
Table has been rebuild, items are now sorted so that the buildup parts come first.

**Comment by dralois** [comment]
There were also some items that had the wrong internal name, I fixed that as well.

**Comment by dralois** [comment]
Alright I pushed the fix to my fork, haven't tested if it works yet though. I'll be able to do that and then send a pull request in ~2h.
