### ISSUE TITLE
Implement Determine_ShouldIDefendLane() Function

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#64]
Write the logic for determining when a lane is being pushed by the enemy and when heroes should rotate to defend it. This will be based on number of enemy heroes approaching said tower versus how many allies have TPs available and off cooldown to get there versus how long the tower will survive the onslaught.

**Comment by Keithenneu** [comment]
I'll try to tinker with some global map state stuff. Unless you have other plans on the short term.

**Comment by Nostrademous** [comment]
No, my plans are to fix ganking crash you mentioned... implement Crystal Maiden so we have a full 5 bot team

**Comment by Nostrademous** [comment]
Obviously I haven't touched Crystal Maiden yet. Probably will not if we keep developing with the team of Lina as a support, Drow mid, AM safelane, Viper offlane, BS jungler.

I am working on writing a better Fighting function and win predictor so that we have "better than basic" fight capability

**Comment by Nostrademous** [comment]
Did a little coding here with some example code that's pushed now that does detection of lane pushing based on number of heroes being >= 3 at a given tower/building/ancient. That's not all that good as we need to detect basically any number of heroes with a creep wave beating on the tower; but I just wanted to get some glue in to get this moving.

**Comment by Nostrademous** [comment]
ShouldIDefendLane() returns lane, tower, # of enemies at said tower now for what it detects as a push. Need to write code for Allied response still (TP use vs walking vs ignore the push)

**Comment by Nostrademous** [comment]
I started using a hero variable called "ShouldDefend" (similar to how "ShouldPush" already exists) to track when we are in a different mode. Plan to use that idea when implementing this.

**Comment by Nostrademous** [comment]
Added code for detecting if heroes can make it to building to defend in time via walking or TPing
