### ISSUE TITLE
Don't Use Flask/Clarity when under a DoT Modifier

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#65]
Don't use a flask/clarity when under a Damage over Time effect (like Shadow Word from Warlock)

**Comment by pbenologa** [comment]
I'm making a list of all DoT Modifier in "utility.lua". Should i also add a method in "utility.lua" that check if there are any DoT modifier present or add the method directly under "item_usage.lua"?

**Comment by Nostrademous** [comment]
I would honestly make a separate file for this called "modifiers.lua" or something. Since we will need to use this in various cases (not just for regen item use).

There is a list of all modifiers here: https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/Built-In_Modifier_Names

I wouldn't do them all for now and wouldn't make a giant list. Just separate list for DoTs (shadow word, shadow strike, viper's dot, etc), Stackable Modifiers (e.g., modifier_shadow_demon_demonic_purge_charge_counter), Unique/Critical one (like BS rupture)

**Comment by pbenologa** [comment]
Yup thanks for the link, I also used that as reference for the DoT modifiers. I'll update the codes by morning.
