### ISSUE TITLE
Implement code to let bots check if they already have some of the required items

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#66]
I played around with the bots, and I noticed Anti-Mage buying two quelling blades - and I looked into your code, starting items quelling blade and then bfury as item. So I guess you do not check if you already have some of the required items, right?

**Comment by Nostrademous** [comment]
I believe this is already being worked on. Not done yet though

**Comment by dralois** [comment]
Yup that is something I'll look into, seems like there is a bug with the boughtitems table. I'm currently not home so that'll take a day or two

**Comment by Nostrademous** [comment]
Supposedly fixed

**Comment by dralois** [comment]
I haven't tried it yet but I think that nested items won't work with this fix. Reason being is that if you buy ring of basilius first and then roa the name doesn't match (since I split it up into parts). I have an idea how to fix that though.
