### ISSUE TITLE
Action Transitioning Signals

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#68]
Is there a way of telling when an Action gets paused and resumed?
Jungling_generic has a state where it just clears creeps around the hero.
If it is dirsrupted during that (by ACTION_GANKING or smth), and resumed while being on a lane, it'll just attack enemy creeps while thinking it's clearing a camp. (resulting in declaring the camp cleared at the end as well)

**Comment by Nostrademous** [comment]
There is a GetAction() and getPrevAction() that will give you the transition

**Comment by Nostrademous** [comment]
There is also a PrintActionTransition function which just prints to console, but we could use it to return a Boolean informing the bot a transition occurred so they can do some checks

**Comment by Keithenneu** [comment]
Ok I'll go with GetAction() and getPrevAction().
Thanks.

**Comment by Nostrademous** [comment]
Sure, I suggest though you only check when a PrintActionTransition occurs so our code is more efficient

**Comment by Nostrademous** [comment]
Also, I started the wiki on Action Stack... still needs more but at least it is a start

**Comment by Nostrademous** [comment]
Hope you don't mind, I pushed some changes to Bloodseeker's ganking code for cleaner ACTION transitions.

**Comment by Keithenneu** [comment]
Thats's great, I actually feel sorry for making you do this :D
Just felt like having some problems would help with getting the action stuff better.

**Comment by Nostrademous** [comment]
I don't mind dude... you crank out code like crazy and I realize I'm probably best positioned to tweak the action state transitions. It's all good.

Also, he plays really well now. Need to add use of Shadow Blade next :P
