### ISSUE TITLE
Discord or any means of communication within contributors

### ISSUE THREAD

**Issue by pbenologa** [Nostrademous/Dota2-FullOverwrite#74]
Hope we can have a chat group where we can communicate directly. Since i still dont have any internet yet at home im doing this at office on my free time.

**Comment by Nostrademous** [comment]
Sorry, you can catch me here very often as I check very frequently. I can't do group chats easily as I co-run a company and have too many other consistent comms channels open that his would be too much of a distraction.

**Comment by pbenologa** [comment]
Oh I see. So i'll just post here if i have any concerns. Thanks!
