### ISSUE TITLE
Create Phantom Assassin bot

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#77]
I asked a lot of people on reddit.com/r/DotA2AI if they could create a Phantom Assassin bot (pa is my favourite hero), which can properly lasthit with her dagger if outzoned.
I want PA bot to destroy me like every PA bot destroys me I meet in pubs. Like I have a 70 % winrate with pa, but AGAINST pa something like that too....

Also a thing about carries I would like to see: I do not want them (like regular bots) to stop lasthitting after 8 minutes, and buying tp's to help the team with no items, die, repeat.
They should farm until they have their core items. AM for example. Let him get bfury and treads, then let him farm jungle until he has manta. Maybe consider really easy pickoffs, but do not make any risks, not even follow anyone who is nearly dead through towers, because stuns, or heroes could gank.
Also as I saw you will add stacking and pulling, if a bot farms jungle and notices it is x:54 or smthg, then he should try to stack, before killing it.
Another thing, no random buybacks early on for carries with no items. Only buyback if they can really help. About that: I see valve's bots buyback, and then just stand around. Only buyback if you are very sure you can actually do something. E.g. 1. whole team is dead, only lion has buyback - DO NOT buyback.
2. Whole team is dead, everyone has buyback, but enigma has no ultimate - NO ONE buys back.
3. Whole team is dead, everyone except carry can buyback - do not buyback.
4. Ancient under attack always buy back. same with the last lane of racks

**Comment by pbenologa** [comment]
This is also what I want for carry hero to farm until they finished a certain item then resume pushing or ganking. Im still learning the whole code but in the long run that is my goal.

**Comment by ByBurton** [comment]
I am too stupid and got no time to learn this right now.  :/

**Comment by Nostrademous** [comment]
Changed title - you could really do this. It is not hard. Use bot_viper.lua as template
