### ISSUE TITLE
Tabs or spaces?

### ISSUE THREAD

**Issue by Keithenneu** [Nostrademous/Dota2-FullOverwrite#83]
It's kinda all over the place right now.
I don't care what it is. As long as it's not both.

**Comment by Nostrademous** [comment]
Let's do spaces... they are easier to copy/paste into posts then spaces. I will switch my editor to use spaces for tabs.

**Comment by Nostrademous** [comment]
We would need to pick a day when we all are either working on new files or not highly diverged from branch... as this will replace whole files basically making merging impossible.

**Comment by Keithenneu** [comment]
So, 4 spaces?

**Comment by Nostrademous** [comment]
that's what I've been changing things to
