### ISSUE TITLE
Bloodseeker:DoRetreat Heal Value

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#84]
So there is a small bug here:

local bloodragePct = {0.25, 0.30, 0.35, 0.40}

and 

local bloodrageHeal = bloodragePct[bloodrage.GetLevel()] * neutrals[1]:GetMaxHealth()

the bloodragePct is the "increase in damage", not the heal. The health return is:
0.19 0.21 0.23 0.25

Rather than hard-coding it we could actually look this up using:
local bloodrage = bot:GetAbilityByName("bloodseeker_bloodrage")
local healReturn = bloodrage:GetSpecialValueInt("health_bonus_creep_pct")/100.0

Doing it that way makes us "future proof" if they ever change it without having to change code... however, it's another look up making the code a "TINY" bit slower then a hardcoded value.

**Comment by pbenologa** [comment]
Noted on this. 😊

**Comment by Nostrademous** [comment]
Yeah. I could have fixed it but this way it's a learning experience and knowledge is shared. :)

Also, becareful on using table indexes like you did with "neutrals[1]" without checking that #neutrals > 0. It was causing a crash that had no errors associated with it since the code was just calling garbage memory essentially in that event.

**Comment by pbenologa** [comment]
Oops my bad. As im still not that familiar with how things works and also not having Dotes on my office laptop to debug the codes right away.  Anyway thanks for the shared knowledge. Will update it by tomorrow.

**Comment by Nostrademous** [comment]
There is also the issue that you should check how many neutrals (#neutrals) are around you, b/c it is possible they will kill you faster than you kill the low-health neutral. That just happened to me in a game. The Centaur Leader neutral was almost dead, I got low, but didn't retreat b/c I could kill him before I died in the code estimation... but, the code didn't account for the other two neutral mobs that were there too and that killed me before my next attack could land.
