### ISSUE TITLE
Hard-Coding Values vs LookUps

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#86]
For abilities, you can look up all values using the ability-scoped function of:

* GetSpecialValueInt()
* GetSpecialValueFloat()

All the names can be found in the npc_abilities.txt file located at:
C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\scripts\npc

Doing things via Look-Ups makes us a bit slower, but resistant to future tweaks by Valve when balancing abilities.

Thoughts?

**Comment by Keithenneu** [comment]
I don't think the perfomance impact will be noticeable (Unless we use it a lot in a loop and in that case we could cache it).
It should make the code more readable ("where is this value even coming from?"), and easier to maintain.

**Comment by pbenologa** [comment]
Im cool with doing things via look-up as opposed to hardcoding less rework when a big balancing patch comes.
