### ISSUE TITLE
BS Ability: UseQ()

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#87]
Did you mean to UseQ() on the enemy if we have a target? It ups their DPS (and makes them take more damage) but it is very situational....

Not sure... if it casts it on an Ulted Sven for example, good luck

**Comment by Keithenneu** [comment]
Since we aren't taking risky fights at all at the moment, I think it's safe to do.
It can also be the quickest way to kill sven :D
Evaluating it should wait until we have more advanced fights. For now, I was just annoyed by him not using it.

**Comment by Nostrademous** [comment]
Cool.
