### ISSUE TITLE
Implement Shrine Usage

### ISSUE THREAD

**Issue by Nostrademous** [Nostrademous/Dota2-FullOverwrite#90]
These exist now as of Jan 19, 2017:

unit-scoped GetNearbyShrines( int nRadius, bool bEnemies )
unit-scoped Action_UseShrine( handle hShrine )

global-scoped GetShrine( int, int ) : returns handle
Gets the specified shrine on the specified team.

constants for the first "int" in GetShrine()
SHRINE_BASE_1, SHRINE_BASE_2, SHRINE_BASE_3, SHRINE_BASE_4, SHRINE_BASE_5, SHRINE_JUNGLE_1, and SHRINE_JUNGLE_2

**Comment by dralois** [comment]
Should that be a team action of sorts or what do you think would be the best way to utilize them?

**Comment by pbenologa** [comment]
There are 2 possible cases where we can use this.

1. Before 10 minute mark where bots can use this even when alone. Mostly by mid spellcaster and by harrassed offlane.

2. Mid game where the bots starts grouping up. Here, we check if their health is below a certain threshold and if a lane near the shrine can be pushed more specifically if 2 or more enemy heroes are dead.

**Comment by Nostrademous** [comment]
Jan 26 API Update:
Added GetShrineCooldown() and IsShrineHealing() to the global bot script API.

**Comment by Nostrademous** [comment]
Implemented this... just waiting on a Valve fix so I can test before checking in.

**Comment by Nostrademous** [comment]
Need to fix that type of Action*() I use to start this
