### ISSUE TITLE
Bot Kiting [question]

### ISSUE THREAD

**Issue by pbenologa** [Nostrademous/Dota2-FullOverwrite#93]
How do I get a random location behind a bot?

**Comment by Keithenneu** [comment]
There is a unit-scoped GetFacing() function, as well as some random functions.
With these and some math you should be able to calculate some vectors.
The exact formulas depend on your definition of "random location behind".

**Comment by pbenologa** [comment]
The definition would be get a location behind the bot based on the given distance. Ill try what you suggested. Thanks!

**Comment by Nostrademous** [comment]
Just added a "VectorAway()" into utils. Should do what you want.
