### ISSUE TITLE
Consider Allies for Consumable Healing Items

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#94]
Bots, at least support-bots, should not only use the potions for themselves, but if an ally needs it put them on them. Share Tangoes, put healing potions or clarities on an allied hero, or stuff like that.
I am seriously busy Nostrademous, but I can maybe try to get in in a few weeks.

**Comment by dralois** [comment]
I have a item class "utility items" which will contain things like that, just haven't thought of a way to properly implement that. Utility items will contain potions, tangoes and stuff like that.

**Comment by Nostrademous** [comment]
Seems to be working.
