### ISSUE TITLE
fix: Bots dropping items at secret shop

### ISSUE THREAD

**Issue by ByBurton** [Nostrademous/Dota2-FullOverwrite#95]
I noticed that (Bloodseeker) bot is dropping the vitality booster he wanted to buy for his vanguard after basher. His inventory was full, and I thought a sell process was already implemented. 
edit: Also are both teams using the dire secret shop for some reason?
edit2: also courier is full of items of bloodseeker bot in this case. another iron talon, another set of tangoes, another set or iron branches, and another shadow amulet. (he already has a complete silver edge and stuff.)
edit3: now he has 3 stout shields----
edit4: is he rebuilding all the items he already has / supposed to have? Is that intended?
edit5: his inventory, bag, stash and the courier is full, he is now dropping items in fountain...

**Comment by Keithenneu** [comment]
What should I say, he loves farming.....

I think the item handling is still a work in progress. Not sure though.

**Comment by ByBurton** [comment]
@Keithenneu Look at all my edits. I am testing your bots in 3 matches in a row now, well. Always nearly the same.
Drow and Crystal maiden get fucked over early game, bloodseeker saves team for a while. 
But of course as most of the stuff of your guys bots is not in yet, they do not teamfight or push or smthg, so no win. 
Also because bloodseeker is too stupid to buy stuff. All other bots seeeeeeeemed fine? I  could be wrong.

**Comment by Keithenneu** [comment]
I didn't follow the item buying branch to much. I'll see if I have to adjust the item lists.

**Comment by dralois** [comment]
I think the only bots using my implementation are viper and anti mage right now.

**Comment by Keithenneu** [comment]
oh, ok. Is it ready to be implemented into the bloodseeker bot? Or are you still working on it?

**Comment by dralois** [comment]
Well buying and selling seems to work, I'm still tweaking but starting and core items are being bought correctly, selling seems to work as well. Extensions still need to be fleshed out, so those items are not being bought right now.

**Comment by Keithenneu** [comment]
What do you mean by extensions? (just an example, so i can tell whether it's ready for bs)

**Comment by dralois** [comment]
Basically I want the bots to be able to decide which items are needed (defensive/offensive) and which ones are best in the situation. That will consider the damage the enemy deals, amount of silences and stuns/slows etc. This should allow us to have a bot not buy a bkb every game because it's in his build but rather decide during the game if it will be needed or not. As long as you don't put any items in the extension category bs will buy everything 😄

**Comment by Keithenneu** [comment]
OK, thanks!

**Comment by Nostrademous** [comment]
I switch BS from Jungle to HardCarry once he hits level 25 in role assignment and give him a lane. Apparently in the old purchase system it switches his purchase table from current to HC one and starts buying items from it as if he just started playing. Not sure if new purchase system would handle mid-game bot role changes

**Comment by dralois** [comment]
The new system only checks the role once in the beginning, so mid game change of role shouldn't affect it

**Comment by Nostrademous** [comment]
Okay... we really need to move all item purchasing for all heroes to new system.
