### ISSUE TITLE
Generic, customizable print

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#97]
We need a print function (in utils probably) that only prints information if we want it. Currently there are a lot of prints being spammed and its very hard to keep track, maybe make it so that its tied to only the bots that we want to know stuff from? The more prints we add the less helpful the console gets imo.

**Comment by Nostrademous** [comment]
there is a myPrint() in utility.lua now. It removes the need to pass the the bot's name and adds a timestamp GameTime() to each message it prints. It's variatic (meaning it takes arbitrary number of arguments).

You could add DEBUG_FLAGS to control what "hero" to print things for I guess

**Comment by dralois** [comment]
Sounds good, the console really is kind of a mess right now, I'll change every print I have to use the new myPrint with some sort of flag, maybe that way we can slowly clean up unneeded or unwanted prints.

**Comment by Nostrademous** [comment]
closed - done by myPrint which can have specific bot names to only print info from
